-- AUTO-GENERATED by scripts/gen-schema.mjs — do not edit by hand.
-- Global Klinik D1 schema (transactional data only; website content lives in R2 + KV).
PRAGMA foreign_keys = OFF;

CREATE TABLE IF NOT EXISTS counters (key TEXT PRIMARY KEY, value INTEGER NOT NULL DEFAULT 0);

CREATE TABLE IF NOT EXISTS users (
  id INTEGER PRIMARY KEY,
  username TEXT,
  name TEXT,
  email TEXT,
  phone TEXT,
  role TEXT,
  branch_id TEXT,
  doctor_id TEXT,
  patient_id INTEGER,
  status TEXT DEFAULT 'active',
  totp_enabled INTEGER,
  last_login_at TEXT,
  password_hash TEXT,
  totp_secret TEXT,
  created_at TEXT,
  updated_at TEXT,
  created_by INTEGER
);
CREATE UNIQUE INDEX IF NOT EXISTS ux_users_username ON users(username);
CREATE INDEX IF NOT EXISTS ix_users_role ON users(role);
CREATE INDEX IF NOT EXISTS ix_users_email ON users(email);
CREATE INDEX IF NOT EXISTS ix_users_phone ON users(phone);
CREATE INDEX IF NOT EXISTS ix_users_branch_id ON users(branch_id);

CREATE TABLE IF NOT EXISTS staff (
  id INTEGER PRIMARY KEY,
  name TEXT,
  position TEXT,
  branch_id TEXT,
  nip TEXT,
  nik TEXT,
  str_no TEXT,
  sip_no TEXT,
  phone TEXT,
  email TEXT,
  address TEXT,
  join_date TEXT,
  photo TEXT,
  user_id INTEGER,
  status TEXT DEFAULT 'active',
  created_at TEXT,
  updated_at TEXT,
  created_by INTEGER
);
CREATE INDEX IF NOT EXISTS ix_staff_branch_id ON staff(branch_id);

CREATE TABLE IF NOT EXISTS patients (
  id INTEGER PRIMARY KEY,
  mrn TEXT,
  name TEXT,
  nik TEXT,
  gender TEXT,
  birth_place TEXT,
  birth_date TEXT,
  blood_type TEXT,
  religion TEXT,
  marital_status TEXT,
  occupation TEXT,
  phone TEXT,
  email TEXT,
  address TEXT,
  city TEXT,
  guardian_name TEXT,
  guardian_relation TEXT,
  guardian_phone TEXT,
  allergies TEXT,
  medical_history TEXT,
  payer_type TEXT DEFAULT 'umum',
  insurer_id TEXT,
  insurance_no TEXT,
  bpjs_no TEXT,
  corporate_id INTEGER,
  member_tier TEXT,
  points REAL DEFAULT 0,
  referral_code TEXT,
  referred_by TEXT,
  branch_id TEXT,
  satusehat_id TEXT,
  notes TEXT,
  created_at TEXT,
  updated_at TEXT,
  created_by INTEGER
);
CREATE UNIQUE INDEX IF NOT EXISTS ux_patients_mrn ON patients(mrn);
CREATE INDEX IF NOT EXISTS ix_patients_name ON patients(name);
CREATE INDEX IF NOT EXISTS ix_patients_phone ON patients(phone);
CREATE INDEX IF NOT EXISTS ix_patients_nik ON patients(nik);
CREATE INDEX IF NOT EXISTS ix_patients_branch_id ON patients(branch_id);
CREATE INDEX IF NOT EXISTS ix_patients_bpjs_no ON patients(bpjs_no);

CREATE TABLE IF NOT EXISTS appointments (
  id INTEGER PRIMARY KEY,
  booking_no TEXT,
  date TEXT,
  time TEXT,
  patient_id INTEGER,
  name TEXT,
  phone TEXT,
  email TEXT,
  birth_date TEXT,
  gender TEXT,
  branch_id TEXT,
  poli_id TEXT,
  service_id TEXT,
  doctor_id TEXT,
  type TEXT DEFAULT 'offline',
  status TEXT DEFAULT 'confirmed',
  complaint TEXT,
  notes TEXT,
  coupon TEXT,
  referral TEXT,
  meet_url TEXT,
  source TEXT DEFAULT 'admin',
  visit_id INTEGER,
  checkin_at TEXT,
  reminded INTEGER,
  created_at TEXT,
  updated_at TEXT,
  created_by INTEGER
);
CREATE UNIQUE INDEX IF NOT EXISTS ux_appointments_booking_no ON appointments(booking_no);
CREATE INDEX IF NOT EXISTS ix_appointments_doctor_id_date ON appointments(doctor_id,date);
CREATE INDEX IF NOT EXISTS ix_appointments_branch_id_date ON appointments(branch_id,date);
CREATE INDEX IF NOT EXISTS ix_appointments_patient_id ON appointments(patient_id);
CREATE INDEX IF NOT EXISTS ix_appointments_phone ON appointments(phone);
CREATE INDEX IF NOT EXISTS ix_appointments_status_date ON appointments(status,date);

CREATE TABLE IF NOT EXISTS visits (
  id INTEGER PRIMARY KEY,
  visit_no TEXT,
  queue_no TEXT,
  date TEXT,
  patient_id INTEGER,
  branch_id TEXT,
  poli_id TEXT,
  doctor_id TEXT,
  queue_status TEXT DEFAULT 'waiting',
  status TEXT DEFAULT 'registered',
  payer_type TEXT DEFAULT 'umum',
  insurer_id TEXT,
  complaint TEXT,
  appointment_id INTEGER,
  queue_seq REAL,
  called_at TEXT,
  finished_at TEXT,
  created_at TEXT,
  updated_at TEXT,
  created_by INTEGER
);
CREATE UNIQUE INDEX IF NOT EXISTS ux_visits_visit_no ON visits(visit_no);
CREATE INDEX IF NOT EXISTS ix_visits_branch_id_date ON visits(branch_id,date);
CREATE INDEX IF NOT EXISTS ix_visits_patient_id ON visits(patient_id);
CREATE INDEX IF NOT EXISTS ix_visits_doctor_id_date ON visits(doctor_id,date);
CREATE INDEX IF NOT EXISTS ix_visits_status ON visits(status);

CREATE TABLE IF NOT EXISTS medical_records (
  id INTEGER PRIMARY KEY,
  date TEXT,
  visit_id INTEGER,
  patient_id INTEGER,
  doctor_id TEXT,
  branch_id TEXT,
  vitals TEXT,
  anamnesis TEXT,
  subjective TEXT,
  physical_exam TEXT,
  objective TEXT,
  assessment TEXT,
  plan TEXT,
  diagnoses TEXT,
  procedures TEXT,
  therapy TEXT,
  notes TEXT,
  attachments TEXT,
  status TEXT DEFAULT 'draft',
  signed_at TEXT,
  created_at TEXT,
  updated_at TEXT,
  created_by INTEGER
);
CREATE UNIQUE INDEX IF NOT EXISTS ux_medical_records_visit_id ON medical_records(visit_id);
CREATE INDEX IF NOT EXISTS ix_medical_records_patient_id_date ON medical_records(patient_id,date);
CREATE INDEX IF NOT EXISTS ix_medical_records_doctor_id_date ON medical_records(doctor_id,date);
CREATE INDEX IF NOT EXISTS ix_medical_records_branch_id_date ON medical_records(branch_id,date);

CREATE TABLE IF NOT EXISTS prescriptions (
  id INTEGER PRIMARY KEY,
  rx_no TEXT,
  date TEXT,
  patient_id INTEGER,
  visit_id INTEGER,
  doctor_id TEXT,
  branch_id TEXT,
  items TEXT,
  status TEXT DEFAULT 'new',
  notes TEXT,
  dispensed_by TEXT,
  dispensed_at TEXT,
  created_at TEXT,
  updated_at TEXT,
  created_by INTEGER
);
CREATE UNIQUE INDEX IF NOT EXISTS ux_prescriptions_rx_no ON prescriptions(rx_no);
CREATE INDEX IF NOT EXISTS ix_prescriptions_branch_id_status ON prescriptions(branch_id,status);
CREATE INDEX IF NOT EXISTS ix_prescriptions_patient_id ON prescriptions(patient_id);
CREATE INDEX IF NOT EXISTS ix_prescriptions_visit_id ON prescriptions(visit_id);
CREATE INDEX IF NOT EXISTS ix_prescriptions_date ON prescriptions(date);

CREATE TABLE IF NOT EXISTS lab_orders (
  id INTEGER PRIMARY KEY,
  lab_no TEXT,
  date TEXT,
  patient_id INTEGER,
  visit_id INTEGER,
  doctor_id TEXT,
  branch_id TEXT,
  tests TEXT,
  status TEXT DEFAULT 'requested',
  notes TEXT,
  validated_by TEXT,
  result_at TEXT,
  created_at TEXT,
  updated_at TEXT,
  created_by INTEGER
);
CREATE UNIQUE INDEX IF NOT EXISTS ux_lab_orders_lab_no ON lab_orders(lab_no);
CREATE INDEX IF NOT EXISTS ix_lab_orders_branch_id_status ON lab_orders(branch_id,status);
CREATE INDEX IF NOT EXISTS ix_lab_orders_patient_id ON lab_orders(patient_id);
CREATE INDEX IF NOT EXISTS ix_lab_orders_visit_id ON lab_orders(visit_id);
CREATE INDEX IF NOT EXISTS ix_lab_orders_date ON lab_orders(date);

CREATE TABLE IF NOT EXISTS invoices (
  id INTEGER PRIMARY KEY,
  invoice_no TEXT,
  date TEXT,
  patient_id INTEGER,
  customer_name TEXT,
  visit_id INTEGER,
  branch_id TEXT,
  type TEXT DEFAULT 'visit',
  items TEXT,
  subtotal REAL,
  discount REAL DEFAULT 0,
  tax REAL,
  total REAL,
  paid REAL,
  status TEXT DEFAULT 'unpaid',
  payer_type TEXT DEFAULT 'umum',
  insurer_id TEXT,
  coupon TEXT,
  notes TEXT,
  pdf_key TEXT,
  created_at TEXT,
  updated_at TEXT,
  created_by INTEGER
);
CREATE UNIQUE INDEX IF NOT EXISTS ux_invoices_invoice_no ON invoices(invoice_no);
CREATE INDEX IF NOT EXISTS ix_invoices_branch_id_date ON invoices(branch_id,date);
CREATE INDEX IF NOT EXISTS ix_invoices_patient_id ON invoices(patient_id);
CREATE INDEX IF NOT EXISTS ix_invoices_visit_id ON invoices(visit_id);
CREATE INDEX IF NOT EXISTS ix_invoices_status_date ON invoices(status,date);

CREATE TABLE IF NOT EXISTS payments (
  id INTEGER PRIMARY KEY,
  payment_no TEXT,
  date TEXT,
  invoice_id INTEGER,
  patient_id INTEGER,
  branch_id TEXT,
  method TEXT,
  amount REAL,
  status TEXT DEFAULT 'confirmed',
  reference TEXT,
  proof TEXT,
  gateway_ref TEXT,
  confirmed_by TEXT,
  notes TEXT,
  created_at TEXT,
  updated_at TEXT,
  created_by INTEGER
);
CREATE UNIQUE INDEX IF NOT EXISTS ux_payments_payment_no ON payments(payment_no);
CREATE INDEX IF NOT EXISTS ix_payments_invoice_id ON payments(invoice_id);
CREATE INDEX IF NOT EXISTS ix_payments_branch_id_date ON payments(branch_id,date);
CREATE INDEX IF NOT EXISTS ix_payments_status ON payments(status);
CREATE INDEX IF NOT EXISTS ix_payments_gateway_ref ON payments(gateway_ref);

CREATE TABLE IF NOT EXISTS refunds (
  id INTEGER PRIMARY KEY,
  refund_no TEXT,
  date TEXT,
  payment_id INTEGER,
  invoice_id INTEGER,
  branch_id TEXT,
  amount REAL,
  reason TEXT,
  status TEXT DEFAULT 'processed',
  processed_by TEXT,
  created_at TEXT,
  updated_at TEXT,
  created_by INTEGER
);
CREATE UNIQUE INDEX IF NOT EXISTS ux_refunds_refund_no ON refunds(refund_no);
CREATE INDEX IF NOT EXISTS ix_refunds_invoice_id ON refunds(invoice_id);
CREATE INDEX IF NOT EXISTS ix_refunds_payment_id ON refunds(payment_id);
CREATE INDEX IF NOT EXISTS ix_refunds_branch_id ON refunds(branch_id);

CREATE TABLE IF NOT EXISTS claims (
  id INTEGER PRIMARY KEY,
  claim_no TEXT,
  date TEXT,
  invoice_id INTEGER,
  patient_id INTEGER,
  insurer_id TEXT,
  branch_id TEXT,
  member_no TEXT,
  sep_no TEXT,
  amount REAL,
  approved_amount REAL,
  status TEXT DEFAULT 'draft',
  submitted_at TEXT,
  notes TEXT,
  created_at TEXT,
  updated_at TEXT,
  created_by INTEGER
);
CREATE UNIQUE INDEX IF NOT EXISTS ux_claims_claim_no ON claims(claim_no);
CREATE INDEX IF NOT EXISTS ix_claims_insurer_id_status ON claims(insurer_id,status);
CREATE INDEX IF NOT EXISTS ix_claims_invoice_id ON claims(invoice_id);
CREATE INDEX IF NOT EXISTS ix_claims_branch_id ON claims(branch_id);

CREATE TABLE IF NOT EXISTS medicines (
  id INTEGER PRIMARY KEY,
  code TEXT,
  name TEXT,
  generic_name TEXT,
  category TEXT,
  form TEXT,
  strength TEXT,
  unit TEXT,
  manufacturer TEXT,
  price_buy REAL,
  price_sell REAL,
  min_stock REAL DEFAULT 10,
  requires_rx INTEGER,
  kfa_code TEXT,
  is_active INTEGER DEFAULT 1,
  created_at TEXT,
  updated_at TEXT,
  created_by INTEGER
);
CREATE UNIQUE INDEX IF NOT EXISTS ux_medicines_code ON medicines(code);
CREATE INDEX IF NOT EXISTS ix_medicines_name ON medicines(name);
CREATE INDEX IF NOT EXISTS ix_medicines_category ON medicines(category);

CREATE TABLE IF NOT EXISTS stock_batches (
  id INTEGER PRIMARY KEY,
  medicine_id INTEGER,
  branch_id TEXT,
  batch_no TEXT,
  expired_at TEXT,
  qty REAL DEFAULT 0 CHECK (qty >= 0),
  cost REAL,
  supplier_id INTEGER,
  created_at TEXT,
  updated_at TEXT,
  created_by INTEGER
);
CREATE INDEX IF NOT EXISTS ix_stock_batches_medicine_id_branch_id_expired_at ON stock_batches(medicine_id,branch_id,expired_at);
CREATE INDEX IF NOT EXISTS ix_stock_batches_branch_id_expired_at ON stock_batches(branch_id,expired_at);

CREATE TABLE IF NOT EXISTS stock_moves (
  id INTEGER PRIMARY KEY,
  date TEXT,
  medicine_id INTEGER,
  branch_id TEXT,
  batch_id INTEGER,
  type TEXT,
  qty REAL,
  balance REAL,
  ref TEXT,
  note TEXT,
  user_name TEXT,
  created_at TEXT,
  updated_at TEXT,
  created_by INTEGER
);
CREATE INDEX IF NOT EXISTS ix_stock_moves_medicine_id_created_at ON stock_moves(medicine_id,created_at);
CREATE INDEX IF NOT EXISTS ix_stock_moves_branch_id_date ON stock_moves(branch_id,date);
CREATE INDEX IF NOT EXISTS ix_stock_moves_type_date ON stock_moves(type,date);

CREATE TABLE IF NOT EXISTS suppliers (
  id INTEGER PRIMARY KEY,
  name TEXT,
  contact TEXT,
  phone TEXT,
  email TEXT,
  address TEXT,
  npwp TEXT,
  terms TEXT,
  active INTEGER DEFAULT 1,
  created_at TEXT,
  updated_at TEXT,
  created_by INTEGER
);

CREATE TABLE IF NOT EXISTS purchase_orders (
  id INTEGER PRIMARY KEY,
  po_no TEXT,
  date TEXT,
  supplier_id INTEGER,
  branch_id TEXT,
  items TEXT,
  total REAL,
  status TEXT DEFAULT 'draft',
  received_at TEXT,
  notes TEXT,
  created_at TEXT,
  updated_at TEXT,
  created_by INTEGER
);
CREATE UNIQUE INDEX IF NOT EXISTS ux_purchase_orders_po_no ON purchase_orders(po_no);
CREATE INDEX IF NOT EXISTS ix_purchase_orders_branch_id_date ON purchase_orders(branch_id,date);
CREATE INDEX IF NOT EXISTS ix_purchase_orders_supplier_id ON purchase_orders(supplier_id);
CREATE INDEX IF NOT EXISTS ix_purchase_orders_status ON purchase_orders(status);

CREATE TABLE IF NOT EXISTS coupons (
  id INTEGER PRIMARY KEY,
  code TEXT,
  description TEXT,
  type TEXT DEFAULT 'percent',
  value REAL,
  min_amount REAL DEFAULT 0,
  max_uses REAL DEFAULT 0,
  used REAL DEFAULT 0,
  start_date TEXT,
  end_date TEXT,
  active INTEGER DEFAULT 1,
  created_at TEXT,
  updated_at TEXT,
  created_by INTEGER
);
CREATE UNIQUE INDEX IF NOT EXISTS ux_coupons_code ON coupons(code);

CREATE TABLE IF NOT EXISTS corporates (
  id INTEGER PRIMARY KEY,
  name TEXT,
  contact TEXT,
  phone TEXT,
  email TEXT,
  address TEXT,
  discount_pct REAL DEFAULT 0,
  contract_until TEXT,
  notes TEXT,
  active INTEGER DEFAULT 1,
  created_at TEXT,
  updated_at TEXT,
  created_by INTEGER
);

CREATE TABLE IF NOT EXISTS leads (
  id INTEGER PRIMARY KEY,
  date TEXT,
  name TEXT,
  phone TEXT,
  email TEXT,
  source TEXT,
  interest TEXT,
  message TEXT,
  status TEXT DEFAULT 'new',
  notes TEXT,
  created_at TEXT,
  updated_at TEXT,
  created_by INTEGER
);
CREATE INDEX IF NOT EXISTS ix_leads_status_date ON leads(status,date);

CREATE TABLE IF NOT EXISTS newsletter (
  id INTEGER PRIMARY KEY,
  email TEXT,
  name TEXT,
  status TEXT DEFAULT 'subscribed',
  created_at TEXT,
  updated_at TEXT,
  created_by INTEGER
);
CREATE UNIQUE INDEX IF NOT EXISTS ux_newsletter_email ON newsletter(email);

CREATE TABLE IF NOT EXISTS documents (
  id INTEGER PRIMARY KEY,
  title TEXT,
  patient_id INTEGER,
  visit_id INTEGER,
  category TEXT,
  file TEXT,
  shared_with_patient INTEGER DEFAULT 1,
  notes TEXT,
  uploaded_by TEXT,
  created_at TEXT,
  updated_at TEXT,
  created_by INTEGER
);
CREATE INDEX IF NOT EXISTS ix_documents_patient_id ON documents(patient_id);
CREATE INDEX IF NOT EXISTS ix_documents_visit_id ON documents(visit_id);

CREATE TABLE IF NOT EXISTS loyalty_ledger (
  id INTEGER PRIMARY KEY,
  patient_id INTEGER,
  points REAL,
  reason TEXT,
  ref TEXT,
  created_at TEXT,
  updated_at TEXT,
  created_by INTEGER
);
CREATE INDEX IF NOT EXISTS ix_loyalty_ledger_patient_id ON loyalty_ledger(patient_id);

CREATE TABLE IF NOT EXISTS notif_log (
  id INTEGER PRIMARY KEY,
  channel TEXT,
  recipient TEXT,
  subject TEXT,
  body TEXT,
  status TEXT,
  ref TEXT,
  link TEXT,
  created_at TEXT,
  updated_at TEXT,
  created_by INTEGER
);
CREATE INDEX IF NOT EXISTS ix_notif_log_created_at ON notif_log(created_at);

CREATE TABLE IF NOT EXISTS satusehat_sync (
  id INTEGER PRIMARY KEY,
  resource TEXT,
  local_id TEXT,
  fhir_id TEXT,
  status TEXT,
  attempts REAL,
  error TEXT,
  created_at TEXT,
  updated_at TEXT,
  created_by INTEGER
);
CREATE INDEX IF NOT EXISTS ix_satusehat_sync_status ON satusehat_sync(status);
CREATE INDEX IF NOT EXISTS ix_satusehat_sync_resource_local_id ON satusehat_sync(resource,local_id);

CREATE TABLE IF NOT EXISTS audit_logs (
  id INTEGER PRIMARY KEY,
  date TEXT,
  username TEXT,
  role TEXT,
  action TEXT,
  entity TEXT,
  entity_id TEXT,
  ip TEXT,
  detail TEXT,
  user_id REAL,
  created_at TEXT,
  updated_at TEXT,
  created_by INTEGER
);
CREATE INDEX IF NOT EXISTS ix_audit_logs_date ON audit_logs(date);
CREATE INDEX IF NOT EXISTS ix_audit_logs_entity_entity_id ON audit_logs(entity,entity_id);
CREATE INDEX IF NOT EXISTS ix_audit_logs_user_id ON audit_logs(user_id);
