// Generates migrations/0001_init.sql from the entity registry so D1 always matches src/schema/entities.js.
// Usage: node scripts/gen-schema.mjs
import { writeFileSync } from 'node:fs';
import { ENTITIES } from '../src/schema/entities.js';

const NUM = new Set(['number', 'money']);
const INT = new Set(['bool']);

function colType(field) {
  if (NUM.has(field.type)) return 'REAL';
  if (INT.has(field.type)) return 'INTEGER';
  if (field.type === 'ref' && ENTITIES[field.ref]?.store === 'd1') return 'INTEGER';
  return 'TEXT';
}

let sql = `-- AUTO-GENERATED by scripts/gen-schema.mjs — do not edit by hand.
-- Global Klinik D1 schema (transactional data only; website content lives in R2 + KV).
PRAGMA foreign_keys = OFF;

CREATE TABLE IF NOT EXISTS counters (key TEXT PRIMARY KEY, value INTEGER NOT NULL DEFAULT 0);
`;

for (const [name, e] of Object.entries(ENTITIES)) {
  if (e.store !== 'd1') continue;
  const cols = ['  id INTEGER PRIMARY KEY'];
  for (const fld of e.fields) {
    if (fld.virtual) continue;
    let def = `  ${fld.key} ${colType(fld)}`;
    if (fld.default !== undefined && typeof fld.default !== 'object') {
      const v = typeof fld.default === 'boolean' ? (fld.default ? 1 : 0) : fld.default;
      def += ` DEFAULT ${typeof v === 'string' ? `'${v.replace(/'/g, "''")}'` : v}`;
    }
    if (fld.check) def += ` CHECK (${fld.check})`;
    cols.push(def);
  }
  cols.push('  created_at TEXT', '  updated_at TEXT', '  created_by INTEGER');
  sql += `\nCREATE TABLE IF NOT EXISTS ${name} (\n${cols.join(',\n')}\n);\n`;
  for (const u of e.unique || []) sql += `CREATE UNIQUE INDEX IF NOT EXISTS ux_${name}_${u.replace(/,/g, '_')} ON ${name}(${u});\n`;
  for (const i of e.indexes || []) sql += `CREATE INDEX IF NOT EXISTS ix_${name}_${i.replace(/,/g, '_')} ON ${name}(${i});\n`;
  if (e.branch && !(e.indexes || []).some((i) => i.startsWith(e.branch))) sql += `CREATE INDEX IF NOT EXISTS ix_${name}_${e.branch} ON ${name}(${e.branch});\n`;
}

writeFileSync(new URL('../migrations/0001_init.sql', import.meta.url), sql);
console.log('migrations/0001_init.sql written');
