// ENTITY REGISTRY — single source of truth for storage, API validation, admin UI and permissions.
// store: 'cms' → R2 JSON (source of truth) + KV bundle cache (0 D1 reads for the public site)
// store: 'd1'  → Cloudflare D1 table (transactional data)
// Adding a module = adding an entity here (+ its D1 table via scripts/gen-schema.mjs).

const f = (key, type, label, extra = {}) => ({ key, type, label, ...extra });

// Common option sets: [value, label ID, label EN]
export const OPTIONS = {
  gender: [['L', 'Laki-laki', 'Male'], ['P', 'Perempuan', 'Female']],
  blood: [['A', 'A', 'A'], ['B', 'B', 'B'], ['AB', 'AB', 'AB'], ['O', 'O', 'O'], ['-', 'Tidak tahu', 'Unknown']],
  religion: [['islam', 'Islam', 'Islam'], ['kristen', 'Kristen', 'Protestant'], ['katolik', 'Katolik', 'Catholic'], ['hindu', 'Hindu', 'Hindu'], ['buddha', 'Buddha', 'Buddhist'], ['konghucu', 'Konghucu', 'Confucian'], ['lainnya', 'Lainnya', 'Other']],
  marital: [['single', 'Belum menikah', 'Single'], ['married', 'Menikah', 'Married'], ['divorced', 'Cerai', 'Divorced'], ['widowed', 'Janda/Duda', 'Widowed']],
  payer: [['umum', 'Umum / Pribadi', 'Self-pay'], ['bpjs', 'BPJS Kesehatan', 'BPJS'], ['asuransi', 'Asuransi', 'Insurance'], ['korporat', 'Korporat', 'Corporate']],
  day: [['1', 'Senin', 'Monday'], ['2', 'Selasa', 'Tuesday'], ['3', 'Rabu', 'Wednesday'], ['4', 'Kamis', 'Thursday'], ['5', 'Jumat', 'Friday'], ['6', 'Sabtu', 'Saturday'], ['0', 'Minggu', 'Sunday']],
  apptStatus: [['pending', 'Menunggu konfirmasi', 'Pending'], ['confirmed', 'Terkonfirmasi', 'Confirmed'], ['checked_in', 'Sudah check-in', 'Checked in'], ['in_progress', 'Diperiksa', 'In progress'], ['completed', 'Selesai', 'Completed'], ['cancelled', 'Dibatalkan', 'Cancelled'], ['no_show', 'Tidak hadir', 'No show'], ['waitlist', 'Daftar tunggu', 'Waiting list']],
  apptType: [['offline', 'Datang ke klinik', 'In-clinic'], ['telemedicine', 'Telemedicine (video)', 'Telemedicine (video)']],
  queueStatus: [['waiting', 'Menunggu', 'Waiting'], ['called', 'Dipanggil', 'Called'], ['serving', 'Dilayani', 'Serving'], ['done', 'Selesai', 'Done'], ['skipped', 'Dilewati', 'Skipped']],
  visitStatus: [['registered', 'Terdaftar', 'Registered'], ['triage', 'Triase', 'Triage'], ['examining', 'Pemeriksaan', 'Examining'], ['lab', 'Laboratorium', 'Laboratory'], ['pharmacy', 'Farmasi', 'Pharmacy'], ['billing', 'Kasir', 'Billing'], ['done', 'Selesai', 'Done'], ['cancelled', 'Batal', 'Cancelled']],
  rxStatus: [['new', 'Baru', 'New'], ['prepared', 'Disiapkan', 'Prepared'], ['dispensed', 'Diserahkan', 'Dispensed'], ['cancelled', 'Batal', 'Cancelled']],
  labStatus: [['requested', 'Diminta', 'Requested'], ['sampled', 'Sampel diambil', 'Sampled'], ['completed', 'Selesai', 'Completed'], ['validated', 'Tervalidasi', 'Validated'], ['cancelled', 'Batal', 'Cancelled']],
  invStatus: [['draft', 'Draf', 'Draft'], ['unpaid', 'Belum bayar', 'Unpaid'], ['partial', 'Sebagian', 'Partial'], ['paid', 'Lunas', 'Paid'], ['refunded', 'Refund', 'Refunded'], ['void', 'Batal', 'Void']],
  invType: [['visit', 'Kunjungan', 'Visit'], ['pharmacy', 'Penjualan obat', 'Pharmacy sale'], ['other', 'Lainnya', 'Other']],
  payMethod: [['cash', 'Tunai', 'Cash'], ['transfer', 'Transfer bank', 'Bank transfer'], ['qris', 'QRIS', 'QRIS'], ['va', 'Virtual Account', 'Virtual Account'], ['ewallet', 'E-wallet', 'E-wallet'], ['card', 'Kartu debit/kredit', 'Debit/credit card'], ['insurance', 'Asuransi/BPJS', 'Insurance/BPJS'], ['gateway', 'Payment gateway', 'Payment gateway']],
  payStatus: [['pending', 'Menunggu', 'Pending'], ['confirmed', 'Terkonfirmasi', 'Confirmed'], ['failed', 'Gagal', 'Failed'], ['refunded', 'Refund', 'Refunded']],
  claimStatus: [['draft', 'Draf', 'Draft'], ['submitted', 'Diajukan', 'Submitted'], ['approved', 'Disetujui', 'Approved'], ['rejected', 'Ditolak', 'Rejected'], ['paid', 'Dibayar', 'Paid']],
  poStatus: [['draft', 'Draf', 'Draft'], ['ordered', 'Dipesan', 'Ordered'], ['received', 'Diterima', 'Received'], ['cancelled', 'Batal', 'Cancelled']],
  moveType: [['in', 'Stok masuk', 'Stock in'], ['out', 'Stok keluar', 'Stock out'], ['dispense', 'Dispensing resep', 'Dispensing'], ['sale', 'Penjualan', 'Sale'], ['return', 'Retur', 'Return'], ['adjust', 'Penyesuaian', 'Adjustment'], ['opname', 'Stock opname', 'Stock take'], ['transfer_in', 'Mutasi masuk', 'Transfer in'], ['transfer_out', 'Mutasi keluar', 'Transfer out'], ['expired', 'Kedaluwarsa', 'Expired']],
  leadStatus: [['new', 'Baru', 'New'], ['contacted', 'Dihubungi', 'Contacted'], ['converted', 'Jadi pasien', 'Converted'], ['lost', 'Batal', 'Lost']],
  activeStatus: [['active', 'Aktif', 'Active'], ['suspended', 'Nonaktif', 'Suspended']],
  pubStatus: [['published', 'Terbit', 'Published'], ['draft', 'Draf', 'Draft']],
  testiStatus: [['published', 'Tampil', 'Published'], ['pending', 'Menunggu moderasi', 'Pending']],
  bannerPos: [['home_hero', 'Beranda — Hero', 'Home — Hero'], ['home_strip', 'Beranda — Strip promo', 'Home — Promo strip'], ['popup', 'Popup', 'Popup']],
  couponType: [['percent', 'Persen (%)', 'Percent (%)'], ['fixed', 'Nominal (Rp)', 'Fixed (Rp)']],
  insurerType: [['bpjs', 'BPJS', 'BPJS'], ['asuransi', 'Asuransi swasta', 'Private insurance'], ['korporat', 'Korporat', 'Corporate']],
  roomType: [['periksa', 'Ruang periksa', 'Exam room'], ['tindakan', 'Ruang tindakan', 'Procedure room'], ['lab', 'Laboratorium', 'Laboratory'], ['farmasi', 'Farmasi', 'Pharmacy'], ['tunggu', 'Ruang tunggu', 'Waiting room'], ['lainnya', 'Lainnya', 'Other']],
  performer: [['doctor', 'Dokter', 'Doctor'], ['nurse', 'Perawat', 'Nurse'], ['both', 'Dokter/Perawat', 'Doctor/Nurse']],
  schedType: [['both', 'Klinik & Telemedicine', 'Clinic & Telemedicine'], ['offline', 'Klinik saja', 'Clinic only'], ['telemedicine', 'Telemedicine saja', 'Telemedicine only']],
  itemKind: [['consult', 'Konsultasi', 'Consultation'], ['procedure', 'Tindakan', 'Procedure'], ['medicine', 'Obat', 'Medicine'], ['lab', 'Laboratorium', 'Laboratory'], ['admin', 'Administrasi', 'Admin fee'], ['other', 'Lainnya', 'Other']],
  labFlag: [['', 'Normal', 'Normal'], ['H', 'Tinggi (H)', 'High (H)'], ['L', 'Rendah (L)', 'Low (L)'], ['A', 'Abnormal', 'Abnormal']],
  docCategory: [['lab', 'Hasil lab', 'Lab result'], ['radiology', 'Radiologi', 'Radiology'], ['referral', 'Surat rujukan', 'Referral letter'], ['certificate', 'Surat keterangan', 'Medical certificate'], ['consent', 'Informed consent', 'Informed consent'], ['other', 'Lainnya', 'Other']],
  syncStatus: [['pending', 'Menunggu', 'Pending'], ['sent', 'Terkirim', 'Sent'], ['failed', 'Gagal', 'Failed'], ['skipped', 'Dilewati', 'Skipped']],
  waProvider: [['none', 'Manual (tombol wa.me)', 'Manual (wa.me button)'], ['fonnte', 'Fonnte', 'Fonnte'], ['wablas', 'Wablas', 'Wablas'], ['wacloud', 'WhatsApp Cloud API', 'WhatsApp Cloud API']],
  ssEnv: [['sandbox', 'Sandbox (uji coba)', 'Sandbox'], ['production', 'Production', 'Production']],
};

export const BLOCK_TYPES = [
  ['hero', 'Hero besar', 'Hero'],
  ['richtext', 'Teks / artikel', 'Rich text'],
  ['image', 'Gambar', 'Image'],
  ['cta', 'Ajakan (CTA)', 'Call to action'],
  ['stats', 'Angka statistik', 'Stats'],
  ['features', 'Keunggulan', 'Features'],
  ['services', 'Daftar layanan', 'Services list'],
  ['doctors', 'Daftar dokter', 'Doctors list'],
  ['promos', 'Promo', 'Promotions'],
  ['testimonials', 'Testimoni', 'Testimonials'],
  ['faq', 'FAQ', 'FAQ'],
  ['branches', 'Cabang', 'Branches'],
  ['posts', 'Artikel terbaru', 'Latest posts'],
  ['pricing', 'Paket harga', 'Pricing'],
  ['facilities', 'Fasilitas', 'Facilities'],
  ['gallery', 'Galeri', 'Gallery'],
  ['booking', 'Form booking cepat', 'Quick booking'],
];

// Sidebar groups for the admin app
export const GROUPS = [
  ['clinical', 'Pelayanan', 'Clinical'],
  ['pharmacy', 'Farmasi & Stok', 'Pharmacy & Stock'],
  ['finance', 'Keuangan', 'Finance'],
  ['crm', 'Pasien & CRM', 'Patients & CRM'],
  ['website', 'Konten Website', 'Website Content'],
  ['master', 'Master Data', 'Master Data'],
  ['system', 'Sistem', 'System'],
];

const I = { i18n: true };
const L = { list: true };
const S = { search: true };
const R = { required: true };
const FULL = { width: 'full' };

export const ENTITIES = {
  // ======================= CMS / WEBSITE (R2 + KV) =======================
  settings: {
    store: 'cms', single: true, group: 'system', icon: 'settings', label: ['Pengaturan', 'Settings'],
    fields: [
      f('clinic_name', 'text', ['Nama klinik', 'Clinic name'], { ...R, section: 'identity' }),
      f('tagline', 'text', ['Tagline', 'Tagline'], { ...I, section: 'identity' }),
      f('description', 'textarea', ['Deskripsi singkat', 'Short description'], { ...I, section: 'identity', ...FULL }),
      f('logo', 'image', ['Logo (opsional, default logo bawaan)', 'Logo (optional)'], { section: 'identity' }),
      f('phone', 'phone', ['Telepon', 'Phone'], { section: 'contact' }),
      f('whatsapp', 'phone', ['WhatsApp', 'WhatsApp'], { section: 'contact' }),
      f('email', 'email', ['Email', 'Email'], { section: 'contact' }),
      f('address', 'textarea', ['Alamat pusat', 'Head office address'], { section: 'contact', ...FULL }),
      f('hours', 'text', ['Jam operasional', 'Opening hours'], { ...I, section: 'contact' }),
      f('emergency', 'text', ['Nomor darurat', 'Emergency number'], { section: 'contact' }),
      f('instagram', 'url', ['Instagram', 'Instagram'], { section: 'social' }),
      f('facebook', 'url', ['Facebook', 'Facebook'], { section: 'social' }),
      f('youtube', 'url', ['YouTube', 'YouTube'], { section: 'social' }),
      f('tiktok', 'url', ['TikTok', 'TikTok'], { section: 'social' }),
      f('sale_stamp_enabled', 'bool', ['Tampilkan stempel "Website dijual"', 'Show "For sale" stamp'], { section: 'stamp', default: true }),
      f('sale_stamp_text', 'text', ['Teks stempel', 'Stamp text'], { section: 'stamp' }),
      f('sale_stamp_phone', 'phone', ['Nomor kontak stempel', 'Stamp contact number'], { section: 'stamp' }),
      f('seo_title', 'text', ['Judul SEO', 'SEO title'], { ...I, section: 'seo' }),
      f('seo_description', 'textarea', ['Deskripsi SEO', 'SEO description'], { ...I, section: 'seo', ...FULL }),
      f('og_image', 'image', ['Gambar share (OG)', 'Share image (OG)'], { section: 'seo' }),
      f('ga_id', 'text', ['Google Analytics ID (G-XXXX)', 'Google Analytics ID'], { section: 'seo' }),
      f('nav', 'items', ['Menu navigasi', 'Navigation menu'], { section: 'nav', ...FULL, columns: [f('label', 'text', ['Label', 'Label'], I), f('href', 'text', ['Tautan', 'Link'])] }),
      f('footer_about', 'textarea', ['Teks footer', 'Footer text'], { ...I, section: 'nav', ...FULL }),
      f('bank_accounts', 'items', ['Rekening bank', 'Bank accounts'], { section: 'payment', ...FULL, columns: [f('bank', 'text', ['Bank', 'Bank']), f('number', 'text', ['No. rekening', 'Account no.']), f('holder', 'text', ['Atas nama', 'Holder'])] }),
      f('qris_image', 'image', ['Gambar QRIS', 'QRIS image'], { section: 'payment' }),
      f('tax_percent', 'number', ['Pajak (%)', 'Tax (%)'], { section: 'payment', default: 0 }),
      f('admin_fee', 'money', ['Biaya administrasi per kunjungan', 'Admin fee per visit'], { section: 'payment', default: 0 }),
      f('invoice_note', 'textarea', ['Catatan invoice', 'Invoice note'], { section: 'payment', ...FULL }),
      f('booking_days_ahead', 'number', ['Booking maks. (hari ke depan)', 'Max booking days ahead'], { section: 'booking', default: 30 }),
      f('booking_auto_confirm', 'bool', ['Booking otomatis terkonfirmasi', 'Auto-confirm bookings'], { section: 'booking', default: true }),
      f('reminder_hours', 'number', ['Pengingat (jam sebelum)', 'Reminder (hours before)'], { section: 'booking', default: 24 }),
      f('points_per_10k', 'number', ['Poin loyalitas per Rp10.000', 'Loyalty points per Rp10,000'], { section: 'booking', default: 1 }),
      f('wa_provider', 'select', ['Gateway WhatsApp', 'WhatsApp gateway'], { section: 'integration', options: OPTIONS.waProvider, default: 'none' }),
      f('smtp_host', 'text', ['Server SMTP (email)', 'SMTP server (email)'], { section: 'integration', help: 'Gmail: smtp.gmail.com · Zoho: smtp.zoho.com · Hosting/cPanel: mail.domainanda.com' }),
      f('smtp_port', 'number', ['Port SMTP', 'SMTP port'], { section: 'integration', default: 465, help: '465 (SSL) atau 587 (STARTTLS). Port 25 diblokir Cloudflare.' }),
      f('smtp_user', 'text', ['User SMTP (alamat email)', 'SMTP user (email address)'], { section: 'integration' }),
      f('smtp_pass', 'password', ['Password SMTP', 'SMTP password'], { section: 'integration', virtual: true, help: 'Gmail: pakai App Password 16 huruf. Disimpan terpisah (tidak ikut konten website). Kosongkan bila tidak diubah.' }),
      f('email_from', 'email', ['Email pengirim', 'Sender email'], { section: 'integration', help: 'Kosongkan = sama dengan User SMTP.' }),
      f('satusehat_env', 'select', ['SATU SEHAT environment', 'SATU SEHAT environment'], { section: 'integration', options: OPTIONS.ssEnv, default: 'sandbox' }),
      f('satusehat_org_id', 'text', ['SATU SEHAT Organization ID', 'SATU SEHAT Organization ID'], { section: 'integration' }),
      f('satusehat_enabled', 'bool', ['Aktifkan sinkron SATU SEHAT', 'Enable SATU SEHAT sync'], { section: 'integration' }),
    ],
  },

  pages: {
    store: 'cms', group: 'website', icon: 'layout', label: ['Halaman & Landing', 'Pages & Landing'], labelField: 'title', slugFrom: 'title',
    fields: [
      f('title', 'text', ['Judul', 'Title'], { ...I, ...R, ...L, ...S }),
      f('slug', 'slug', ['Slug URL', 'URL slug'], { ...L, help: 'home = beranda; tentang = halaman Tentang' }),
      f('status', 'select', ['Status', 'Status'], { ...L, options: OPTIONS.pubStatus, default: 'published' }),
      f('seo_description', 'textarea', ['Deskripsi SEO', 'SEO description'], { ...I, ...FULL }),
      f('blocks', 'blocks', ['Blok konten', 'Content blocks'], { heavy: true, ...FULL }),
    ],
  },
  banners: {
    store: 'cms', group: 'website', icon: 'image', label: ['Banner', 'Banners'], labelField: 'title',
    fields: [
      f('title', 'text', ['Judul', 'Title'], { ...I, ...R, ...L, ...S }),
      f('subtitle', 'textarea', ['Subjudul', 'Subtitle'], I),
      f('image', 'image', ['Gambar', 'Image'], L),
      f('cta_label', 'text', ['Label tombol', 'Button label'], I),
      f('cta_href', 'text', ['Tautan tombol', 'Button link']),
      f('position', 'select', ['Posisi', 'Position'], { ...L, options: OPTIONS.bannerPos, default: 'home_strip' }),
      f('start_date', 'date', ['Mulai', 'Start']),
      f('end_date', 'date', ['Selesai', 'End']),
      f('order', 'number', ['Urutan', 'Order'], { default: 0 }),
      f('active', 'bool', ['Aktif', 'Active'], { ...L, default: true }),
    ],
  },
  services: {
    store: 'cms', group: 'website', icon: 'stethoscope', label: ['Layanan', 'Services'], labelField: 'name', slugFrom: 'name',
    fields: [
      f('name', 'text', ['Nama layanan', 'Service name'], { ...I, ...R, ...L, ...S }),
      f('slug', 'slug', ['Slug URL', 'URL slug']),
      f('poli_id', 'ref', ['Poli', 'Clinic unit'], { ref: 'polis', ...L, filter: true }),
      f('icon', 'icon', ['Ikon', 'Icon'], { default: 'stethoscope' }),
      f('image', 'image', ['Gambar', 'Image']),
      f('excerpt', 'textarea', ['Ringkasan', 'Summary'], { ...I, ...FULL }),
      f('content', 'markdown', ['Deskripsi lengkap', 'Full description'], { ...I, heavy: true, ...FULL }),
      f('price', 'money', ['Harga mulai', 'Price from'], L),
      f('price_note', 'text', ['Keterangan harga', 'Price note'], I),
      f('duration', 'number', ['Durasi (menit)', 'Duration (min)'], { default: 30 }),
      f('branch_prices', 'items', ['Harga khusus per cabang', 'Branch-specific prices'], { ...FULL, columns: [f('branch_id', 'ref', ['Cabang', 'Branch'], { ref: 'branches' }), f('price', 'money', ['Harga', 'Price'])] }),
      f('branches', 'refs', ['Tersedia di cabang', 'Available at branches'], { ref: 'branches' }),
      f('telemedicine', 'bool', ['Bisa telemedicine', 'Telemedicine available']),
      f('featured', 'bool', ['Unggulan', 'Featured'], L),
      f('active', 'bool', ['Aktif', 'Active'], { ...L, default: true }),
      f('order', 'number', ['Urutan', 'Order'], { default: 0 }),
    ],
  },
  doctors: {
    store: 'cms', group: 'clinical', icon: 'doctor', label: ['Dokter', 'Doctors'], labelField: 'name', slugFrom: 'name',
    fields: [
      f('name', 'text', ['Nama lengkap & gelar', 'Full name & title'], { ...R, ...L, ...S }),
      f('slug', 'slug', ['Slug URL', 'URL slug']),
      f('specialty', 'text', ['Spesialisasi', 'Specialty'], { ...I, ...L }),
      f('poli_id', 'ref', ['Poli', 'Clinic unit'], { ref: 'polis', ...L, filter: true }),
      f('branches', 'refs', ['Praktik di cabang', 'Practices at'], { ref: 'branches' }),
      f('photo', 'image', ['Foto', 'Photo']),
      f('bio', 'markdown', ['Profil', 'Biography'], { ...I, ...FULL }),
      f('education', 'textarea', ['Pendidikan (1 per baris)', 'Education (1 per line)'], { ...I, ...FULL }),
      f('experience_years', 'number', ['Pengalaman (tahun)', 'Experience (years)']),
      f('languages', 'text', ['Bahasa', 'Languages'], { default: 'Indonesia, English' }),
      f('str_no', 'text', ['No. STR', 'STR no.']),
      f('sip_no', 'text', ['No. SIP', 'SIP no.']),
      f('nik', 'text', ['NIK (SATU SEHAT)', 'NIK (SATU SEHAT)']),
      f('consult_fee', 'money', ['Tarif konsultasi', 'Consultation fee'], L),
      f('telemedicine', 'bool', ['Melayani telemedicine', 'Offers telemedicine']),
      f('rating', 'number', ['Rating (1-5)', 'Rating (1-5)'], { default: 5 }),
      f('featured', 'bool', ['Tampil di beranda', 'Show on home'], { default: true }),
      f('active', 'bool', ['Aktif', 'Active'], { ...L, default: true }),
      f('order', 'number', ['Urutan', 'Order'], { default: 0 }),
    ],
  },
  schedules: {
    store: 'cms', group: 'clinical', icon: 'calendar', label: ['Jadwal Praktik', 'Doctor Schedules'], labelField: 'id',
    fields: [
      f('doctor_id', 'ref', ['Dokter', 'Doctor'], { ref: 'doctors', ...R, ...L, filter: true }),
      f('branch_id', 'ref', ['Cabang', 'Branch'], { ref: 'branches', ...R, ...L, filter: true }),
      f('poli_id', 'ref', ['Poli', 'Clinic unit'], { ref: 'polis', ...L }),
      f('day', 'select', ['Hari', 'Day'], { options: OPTIONS.day, ...R, ...L, filter: true }),
      f('start', 'time', ['Mulai', 'Start'], { ...R, ...L, default: '08:00' }),
      f('end', 'time', ['Selesai', 'End'], { ...R, ...L, default: '12:00' }),
      f('slot_minutes', 'number', ['Durasi slot (menit)', 'Slot length (min)'], { default: 20 }),
      f('quota_per_slot', 'number', ['Kuota per slot', 'Quota per slot'], { default: 1 }),
      f('type', 'select', ['Jenis', 'Type'], { options: OPTIONS.schedType, default: 'both', ...L }),
      f('room_id', 'ref', ['Ruangan', 'Room'], { ref: 'rooms' }),
      f('active', 'bool', ['Aktif', 'Active'], { ...L, default: true }),
    ],
  },
  branches: {
    store: 'cms', group: 'master', icon: 'building', label: ['Cabang', 'Branches'], labelField: 'name', slugFrom: 'name',
    fields: [
      f('name', 'text', ['Nama cabang', 'Branch name'], { ...R, ...L, ...S }),
      f('slug', 'slug', ['Slug URL', 'URL slug']),
      f('code', 'text', ['Kode (untuk nomor dokumen)', 'Code (for numbering)'], { ...R, ...L, help: 'Mis. JKT, BDG — 2-4 huruf' }),
      f('city', 'text', ['Kota', 'City'], L),
      f('address', 'textarea', ['Alamat', 'Address'], FULL),
      f('phone', 'phone', ['Telepon', 'Phone'], L),
      f('whatsapp', 'phone', ['WhatsApp', 'WhatsApp']),
      f('email', 'email', ['Email', 'Email']),
      f('hours', 'text', ['Jam buka', 'Opening hours'], I),
      f('maps_url', 'url', ['URL embed Google Maps', 'Google Maps embed URL'], { ...FULL, help: 'Google Maps → Bagikan → Sematkan peta → salin src' }),
      f('lat', 'number', ['Latitude', 'Latitude']),
      f('lng', 'number', ['Longitude', 'Longitude']),
      f('image', 'image', ['Foto cabang', 'Branch photo']),
      f('is_main', 'bool', ['Kantor pusat', 'Head office'], L),
      f('satusehat_location_id', 'text', ['SATU SEHAT Location ID', 'SATU SEHAT Location ID']),
      f('active', 'bool', ['Aktif', 'Active'], { ...L, default: true }),
      f('order', 'number', ['Urutan', 'Order'], { default: 0 }),
    ],
  },
  polis: {
    store: 'cms', group: 'master', icon: 'grid', label: ['Poli / Unit', 'Clinic Units'], labelField: 'name',
    fields: [
      f('name', 'text', ['Nama poli', 'Unit name'], { ...I, ...R, ...L, ...S }),
      f('code', 'text', ['Kode antrian', 'Queue prefix'], { ...R, ...L, help: 'Huruf awalan nomor antrian, mis. A, B, C' }),
      f('icon', 'icon', ['Ikon', 'Icon'], { default: 'stethoscope' }),
      f('color', 'color', ['Warna', 'Color'], { default: '#0F766E' }),
      f('description', 'textarea', ['Deskripsi', 'Description'], { ...I, ...FULL }),
      f('branches', 'refs', ['Cabang', 'Branches'], { ref: 'branches' }),
      f('active', 'bool', ['Aktif', 'Active'], { ...L, default: true }),
      f('order', 'number', ['Urutan', 'Order'], { default: 0 }),
    ],
  },
  facilities: {
    store: 'cms', group: 'website', icon: 'star', label: ['Fasilitas', 'Facilities'], labelField: 'name',
    fields: [
      f('name', 'text', ['Nama fasilitas', 'Facility'], { ...I, ...R, ...L, ...S }),
      f('description', 'textarea', ['Deskripsi', 'Description'], { ...I, ...FULL }),
      f('icon', 'icon', ['Ikon', 'Icon'], { default: 'star' }),
      f('image', 'image', ['Foto', 'Photo'], L),
      f('branches', 'refs', ['Cabang', 'Branches'], { ref: 'branches' }),
      f('order', 'number', ['Urutan', 'Order'], { default: 0 }),
      f('active', 'bool', ['Aktif', 'Active'], { ...L, default: true }),
    ],
  },
  pricing: {
    store: 'cms', group: 'website', icon: 'tag', label: ['Paket Harga', 'Pricing Packages'], labelField: 'name',
    fields: [
      f('name', 'text', ['Nama paket', 'Package name'], { ...I, ...R, ...L, ...S }),
      f('description', 'textarea', ['Deskripsi', 'Description'], I),
      f('price', 'money', ['Harga', 'Price'], { ...R, ...L }),
      f('price_old', 'money', ['Harga coret', 'Old price']),
      f('features', 'textarea', ['Fitur (1 per baris)', 'Features (1 per line)'], { ...I, ...FULL }),
      f('service_id', 'ref', ['Layanan terkait', 'Related service'], { ref: 'services' }),
      f('highlight', 'bool', ['Paling populer', 'Most popular'], L),
      f('order', 'number', ['Urutan', 'Order'], { default: 0 }),
      f('active', 'bool', ['Aktif', 'Active'], { ...L, default: true }),
    ],
  },
  promotions: {
    store: 'cms', group: 'website', icon: 'gift', label: ['Promo', 'Promotions'], labelField: 'title', slugFrom: 'title',
    fields: [
      f('title', 'text', ['Judul promo', 'Title'], { ...I, ...R, ...L, ...S }),
      f('slug', 'slug', ['Slug URL', 'URL slug']),
      f('excerpt', 'textarea', ['Ringkasan', 'Summary'], { ...I, ...FULL }),
      f('content', 'markdown', ['Detail & syarat', 'Details & terms'], { ...I, heavy: true, ...FULL }),
      f('image', 'image', ['Gambar', 'Image'], L),
      f('badge', 'text', ['Label (mis. -20%)', 'Badge (e.g. -20%)'], I),
      f('coupon_code', 'text', ['Kode kupon', 'Coupon code'], L),
      f('start_date', 'date', ['Mulai', 'Start'], L),
      f('end_date', 'date', ['Berakhir', 'End'], L),
      f('active', 'bool', ['Aktif', 'Active'], { ...L, default: true }),
    ],
  },
  testimonials: {
    store: 'cms', group: 'website', icon: 'quote', label: ['Testimoni', 'Testimonials'], labelField: 'name',
    fields: [
      f('name', 'text', ['Nama', 'Name'], { ...R, ...L, ...S }),
      f('caption', 'text', ['Keterangan (mis. Pasien Poli Gigi)', 'Caption'], I),
      f('rating', 'number', ['Rating (1-5)', 'Rating (1-5)'], { ...L, default: 5, min: 1, max: 5 }),
      f('content', 'textarea', ['Testimoni', 'Testimonial'], { ...I, ...R, ...FULL }),
      f('photo', 'image', ['Foto', 'Photo']),
      f('status', 'select', ['Status', 'Status'], { ...L, options: OPTIONS.testiStatus, default: 'published', filter: true }),
      f('date', 'date', ['Tanggal', 'Date'], L),
    ],
  },
  posts: {
    store: 'cms', group: 'website', icon: 'file', label: ['Blog & Artikel', 'Blog & Articles'], labelField: 'title', slugFrom: 'title',
    fields: [
      f('title', 'text', ['Judul', 'Title'], { ...I, ...R, ...L, ...S }),
      f('slug', 'slug', ['Slug URL', 'URL slug']),
      f('category', 'text', ['Kategori', 'Category'], { ...L, filter: true }),
      f('tags', 'tags', ['Tag', 'Tags']),
      f('cover', 'image', ['Gambar sampul', 'Cover image']),
      f('excerpt', 'textarea', ['Ringkasan', 'Excerpt'], { ...I, ...FULL }),
      f('content', 'markdown', ['Isi artikel', 'Content'], { ...I, heavy: true, ...FULL }),
      f('author', 'text', ['Penulis', 'Author'], L),
      f('published_at', 'date', ['Tanggal terbit', 'Publish date'], L),
      f('status', 'select', ['Status', 'Status'], { ...L, options: OPTIONS.pubStatus, default: 'published', filter: true }),
    ],
  },
  faqs: {
    store: 'cms', group: 'website', icon: 'help', label: ['FAQ', 'FAQ'], labelField: 'question',
    fields: [
      f('question', 'text', ['Pertanyaan', 'Question'], { ...I, ...R, ...L, ...S, ...FULL }),
      f('answer', 'markdown', ['Jawaban', 'Answer'], { ...I, ...R, ...FULL }),
      f('category', 'text', ['Kategori', 'Category'], { ...L, filter: true }),
      f('order', 'number', ['Urutan', 'Order'], { default: 0 }),
      f('active', 'bool', ['Aktif', 'Active'], { ...L, default: true }),
    ],
  },
  holidays: {
    store: 'cms', group: 'master', icon: 'calendar-off', label: ['Libur & Cuti Dokter', 'Holidays & Leave'], labelField: 'name',
    fields: [
      f('date', 'date', ['Tanggal', 'Date'], { ...R, ...L }),
      f('date_end', 'date', ['Sampai tanggal', 'Until'], L),
      f('name', 'text', ['Keterangan', 'Description'], { ...R, ...L, ...S }),
      f('branch_id', 'ref', ['Cabang (kosong = semua)', 'Branch (empty = all)'], { ref: 'branches', ...L }),
      f('doctor_id', 'ref', ['Dokter (cuti)', 'Doctor (leave)'], { ref: 'doctors', ...L }),
    ],
  },
  rooms: {
    store: 'cms', group: 'master', icon: 'door', label: ['Ruangan', 'Rooms'], labelField: 'name',
    fields: [
      f('name', 'text', ['Nama ruangan', 'Room name'], { ...R, ...L, ...S }),
      f('branch_id', 'ref', ['Cabang', 'Branch'], { ref: 'branches', ...R, ...L, filter: true }),
      f('poli_id', 'ref', ['Poli', 'Unit'], { ref: 'polis', ...L }),
      f('type', 'select', ['Jenis', 'Type'], { options: OPTIONS.roomType, ...L }),
      f('capacity', 'number', ['Kapasitas', 'Capacity'], { default: 1 }),
      f('active', 'bool', ['Aktif', 'Active'], { ...L, default: true }),
    ],
  },
  procedures: {
    store: 'cms', group: 'master', icon: 'activity', label: ['Tindakan & Tarif', 'Procedures & Fees'], labelField: 'name',
    fields: [
      f('code', 'text', ['Kode', 'Code'], { ...L, ...S }),
      f('name', 'text', ['Nama tindakan', 'Procedure'], { ...R, ...L, ...S }),
      f('category', 'text', ['Kategori', 'Category'], { ...L, filter: true }),
      f('poli_id', 'ref', ['Poli', 'Unit'], { ref: 'polis', ...L }),
      f('price', 'money', ['Tarif', 'Fee'], { ...R, ...L }),
      f('branch_prices', 'items', ['Tarif per cabang', 'Branch fees'], { ...FULL, columns: [f('branch_id', 'ref', ['Cabang', 'Branch'], { ref: 'branches' }), f('price', 'money', ['Tarif', 'Fee'])] }),
      f('performer', 'select', ['Dilakukan oleh', 'Performed by'], { options: OPTIONS.performer, default: 'doctor' }),
      f('icd9', 'text', ['Kode ICD-9-CM', 'ICD-9-CM code']),
      f('active', 'bool', ['Aktif', 'Active'], { ...L, default: true }),
    ],
  },
  lab_tests: {
    store: 'cms', group: 'master', icon: 'flask', label: ['Pemeriksaan Lab', 'Lab Tests'], labelField: 'name',
    fields: [
      f('code', 'text', ['Kode', 'Code'], { ...L, ...S }),
      f('name', 'text', ['Nama pemeriksaan', 'Test name'], { ...R, ...L, ...S }),
      f('category', 'text', ['Kategori', 'Category'], { ...L, filter: true }),
      f('unit', 'text', ['Satuan', 'Unit'], L),
      f('ref_low', 'number', ['Nilai rujukan bawah', 'Reference low']),
      f('ref_high', 'number', ['Nilai rujukan atas', 'Reference high']),
      f('ref_text', 'text', ['Nilai rujukan (teks)', 'Reference (text)'], L),
      f('price', 'money', ['Tarif', 'Fee'], { ...R, ...L }),
      f('loinc', 'text', ['Kode LOINC', 'LOINC code']),
      f('active', 'bool', ['Aktif', 'Active'], { ...L, default: true }),
    ],
  },
  insurers: {
    store: 'cms', group: 'finance', icon: 'shield', label: ['Penjamin / Asuransi', 'Payers / Insurers'], labelField: 'name',
    fields: [
      f('name', 'text', ['Nama penjamin', 'Payer name'], { ...R, ...L, ...S }),
      f('type', 'select', ['Jenis', 'Type'], { options: OPTIONS.insurerType, ...L, filter: true }),
      f('code', 'text', ['Kode', 'Code'], L),
      f('contact', 'text', ['Kontak', 'Contact']),
      f('phone', 'phone', ['Telepon', 'Phone']),
      f('email', 'email', ['Email', 'Email']),
      f('discount_pct', 'number', ['Diskon (%)', 'Discount (%)'], { default: 0 }),
      f('active', 'bool', ['Aktif', 'Active'], { ...L, default: true }),
    ],
  },
  medicine_categories: {
    store: 'cms', group: 'pharmacy', icon: 'folder', label: ['Kategori Obat', 'Medicine Categories'], labelField: 'name',
    fields: [f('name', 'text', ['Nama kategori', 'Category'], { ...R, ...L, ...S }), f('description', 'text', ['Keterangan', 'Description'], L)],
  },
  units: {
    store: 'cms', group: 'pharmacy', icon: 'box', label: ['Satuan Obat', 'Medicine Units'], labelField: 'name',
    fields: [f('name', 'text', ['Satuan', 'Unit'], { ...R, ...L, ...S })],
  },
  membership_tiers: {
    store: 'cms', group: 'crm', icon: 'award', label: ['Tier Member', 'Membership Tiers'], labelField: 'name',
    fields: [
      f('name', 'text', ['Nama tier', 'Tier'], { ...R, ...L }),
      f('min_points', 'number', ['Minimal poin', 'Min. points'], { ...R, ...L, default: 0 }),
      f('discount_pct', 'number', ['Diskon (%)', 'Discount (%)'], { ...L, default: 0 }),
      f('color', 'color', ['Warna', 'Color'], { default: '#B8893B' }),
      f('benefits', 'textarea', ['Benefit (1 per baris)', 'Benefits (1 per line)'], { ...I, ...FULL }),
    ],
  },
  roles: {
    store: 'cms', group: 'system', icon: 'key', label: ['Peran & Izin', 'Roles & Permissions'], labelField: 'name', idFrom: 'code',
    fields: [
      f('code', 'text', ['Kode peran', 'Role code'], { ...R, ...L, help: 'huruf kecil tanpa spasi, mis. perawat_senior' }),
      f('name', 'text', ['Nama peran', 'Role name'], { ...R, ...L, ...S }),
      f('description', 'text', ['Deskripsi', 'Description'], L),
      f('home', 'text', ['Halaman awal', 'Home screen'], { default: 'dashboard' }),
      f('perms', 'perms', ['Izin akses', 'Permissions'], FULL),
    ],
  },

  // ======================= D1 (transactional) =======================
  users: {
    store: 'd1', group: 'system', icon: 'user-cog', label: ['Pengguna', 'Users'], labelField: 'name', branch: 'branch_id',
    unique: ['username'], indexes: ['role', 'email', 'phone'],
    fields: [
      f('username', 'text', ['Username', 'Username'], { ...R, ...L, ...S }),
      f('name', 'text', ['Nama', 'Name'], { ...R, ...L, ...S }),
      f('email', 'email', ['Email', 'Email'], { ...L, ...S }),
      f('phone', 'phone', ['No. HP', 'Phone']),
      f('role', 'select', ['Peran', 'Role'], { ...R, ...L, optionsFrom: 'roles', filter: true }),
      f('branch_id', 'ref', ['Cabang (kosong = semua)', 'Branch (empty = all)'], { ref: 'branches', ...L }),
      f('doctor_id', 'ref', ['Profil dokter', 'Doctor profile'], { ref: 'doctors' }),
      f('patient_id', 'ref', ['Data pasien', 'Patient record'], { ref: 'patients' }),
      f('password', 'password', ['Password / PIN (isi untuk mengganti, min. 4 karakter)', 'Password / PIN (fill to change, min. 4 characters)'], { virtual: true }),
      f('status', 'select', ['Status', 'Status'], { options: OPTIONS.activeStatus, default: 'active', ...L, filter: true }),
      f('totp_enabled', 'bool', ['2FA aktif', '2FA enabled'], { readonly: true, ...L }),
      f('last_login_at', 'datetime', ['Login terakhir', 'Last login'], { readonly: true, ...L }),
      f('password_hash', 'hidden', ['', ''], { hidden: true, secret: true }),
      f('totp_secret', 'hidden', ['', ''], { hidden: true, secret: true }),
    ],
  },
  staff: {
    store: 'd1', group: 'crm', icon: 'id-card', label: ['Staf & Karyawan', 'Staff'], labelField: 'name', branch: 'branch_id', indexes: ['branch_id'],
    fields: [
      f('name', 'text', ['Nama', 'Name'], { ...R, ...L, ...S }),
      f('position', 'text', ['Jabatan', 'Position'], { ...L, ...S }),
      f('branch_id', 'ref', ['Cabang', 'Branch'], { ref: 'branches', ...L, filter: true }),
      f('nip', 'text', ['NIP', 'Employee ID'], L),
      f('nik', 'text', ['NIK', 'National ID']),
      f('str_no', 'text', ['No. STR', 'STR no.']),
      f('sip_no', 'text', ['No. SIP', 'SIP no.']),
      f('phone', 'phone', ['No. HP', 'Phone'], L),
      f('email', 'email', ['Email', 'Email']),
      f('address', 'textarea', ['Alamat', 'Address'], FULL),
      f('join_date', 'date', ['Tanggal masuk', 'Join date']),
      f('photo', 'image', ['Foto', 'Photo']),
      f('user_id', 'ref', ['Akun pengguna', 'User account'], { ref: 'users' }),
      f('status', 'select', ['Status', 'Status'], { options: OPTIONS.activeStatus, default: 'active', ...L }),
    ],
  },
  patients: {
    store: 'd1', group: 'crm', icon: 'users', label: ['Pasien', 'Patients'], labelField: 'name', labelExtra: 'mrn', branch: 'branch_id',
    unique: ['mrn'], indexes: ['name', 'phone', 'nik', 'branch_id', 'bpjs_no'],
    fields: [
      f('mrn', 'text', ['No. Rekam Medis', 'MRN'], { readonly: true, auto: 'mrn', ...L, ...S }),
      f('name', 'text', ['Nama lengkap', 'Full name'], { ...R, ...L, ...S, section: 'identity' }),
      f('nik', 'text', ['NIK', 'National ID (NIK)'], { ...S, section: 'identity' }),
      f('gender', 'select', ['Jenis kelamin', 'Gender'], { options: OPTIONS.gender, ...L, section: 'identity' }),
      f('birth_place', 'text', ['Tempat lahir', 'Place of birth'], { section: 'identity' }),
      f('birth_date', 'date', ['Tanggal lahir', 'Date of birth'], { ...L, section: 'identity' }),
      f('blood_type', 'select', ['Golongan darah', 'Blood type'], { options: OPTIONS.blood, section: 'identity' }),
      f('religion', 'select', ['Agama', 'Religion'], { options: OPTIONS.religion, section: 'identity' }),
      f('marital_status', 'select', ['Status nikah', 'Marital status'], { options: OPTIONS.marital, section: 'identity' }),
      f('occupation', 'text', ['Pekerjaan', 'Occupation'], { section: 'identity' }),
      f('phone', 'phone', ['No. HP / WA', 'Phone / WA'], { ...L, ...S, section: 'contact' }),
      f('email', 'email', ['Email', 'Email'], { section: 'contact' }),
      f('address', 'textarea', ['Alamat', 'Address'], { ...FULL, section: 'contact' }),
      f('city', 'text', ['Kota', 'City'], { section: 'contact' }),
      f('guardian_name', 'text', ['Nama penanggung jawab', 'Guardian name'], { section: 'guardian' }),
      f('guardian_relation', 'text', ['Hubungan', 'Relation'], { section: 'guardian' }),
      f('guardian_phone', 'phone', ['HP penanggung jawab', 'Guardian phone'], { section: 'guardian' }),
      f('allergies', 'textarea', ['Alergi', 'Allergies'], { section: 'medical' }),
      f('medical_history', 'textarea', ['Riwayat penyakit', 'Medical history'], { section: 'medical' }),
      f('payer_type', 'select', ['Penjamin', 'Payer'], { options: OPTIONS.payer, default: 'umum', ...L, filter: true, section: 'payer' }),
      f('insurer_id', 'ref', ['Asuransi / penjamin', 'Insurer'], { ref: 'insurers', section: 'payer' }),
      f('insurance_no', 'text', ['No. polis / kartu', 'Policy / card no.'], { section: 'payer' }),
      f('bpjs_no', 'text', ['No. BPJS', 'BPJS no.'], { ...S, section: 'payer' }),
      f('corporate_id', 'ref', ['Perusahaan', 'Corporate'], { ref: 'corporates', section: 'payer' }),
      f('member_tier', 'ref', ['Tier member', 'Member tier'], { ref: 'membership_tiers', section: 'crm' }),
      f('points', 'number', ['Poin loyalitas', 'Loyalty points'], { default: 0, section: 'crm' }),
      f('referral_code', 'text', ['Kode referral', 'Referral code'], { readonly: true, section: 'crm' }),
      f('referred_by', 'text', ['Direferensikan oleh (kode)', 'Referred by (code)'], { section: 'crm' }),
      f('branch_id', 'ref', ['Cabang terdaftar', 'Registered branch'], { ref: 'branches', ...L, filter: true, section: 'crm' }),
      f('satusehat_id', 'text', ['IHS Number (SATU SEHAT)', 'IHS Number'], { section: 'crm' }),
      f('notes', 'textarea', ['Catatan', 'Notes'], { ...FULL, section: 'crm' }),
    ],
  },
  appointments: {
    store: 'd1', group: 'clinical', icon: 'calendar-check', label: ['Janji Temu / Booking', 'Appointments'], labelField: 'booking_no', branch: 'branch_id', dateField: 'date',
    unique: ['booking_no'], indexes: ['doctor_id,date', 'branch_id,date', 'patient_id', 'phone', 'status,date'],
    fields: [
      f('booking_no', 'text', ['No. booking', 'Booking no.'], { readonly: true, auto: 'booking', ...L, ...S }),
      f('date', 'date', ['Tanggal', 'Date'], { ...R, ...L }),
      f('time', 'time', ['Jam', 'Time'], { ...R, ...L }),
      f('patient_id', 'ref', ['Pasien terdaftar', 'Registered patient'], { ref: 'patients' }),
      f('name', 'text', ['Nama pasien', 'Patient name'], { ...R, ...L, ...S }),
      f('phone', 'phone', ['No. HP / WA', 'Phone / WA'], { ...R, ...S }),
      f('email', 'email', ['Email', 'Email']),
      f('birth_date', 'date', ['Tanggal lahir', 'Date of birth']),
      f('gender', 'select', ['Jenis kelamin', 'Gender'], { options: OPTIONS.gender }),
      f('branch_id', 'ref', ['Cabang', 'Branch'], { ref: 'branches', ...R, ...L, filter: true }),
      f('poli_id', 'ref', ['Poli', 'Unit'], { ref: 'polis', filter: true }),
      f('service_id', 'ref', ['Layanan', 'Service'], { ref: 'services' }),
      f('doctor_id', 'ref', ['Dokter', 'Doctor'], { ref: 'doctors', ...L, filter: true }),
      f('type', 'select', ['Jenis', 'Type'], { options: OPTIONS.apptType, default: 'offline', ...L }),
      f('status', 'select', ['Status', 'Status'], { options: OPTIONS.apptStatus, default: 'confirmed', ...L, filter: true }),
      f('complaint', 'textarea', ['Keluhan', 'Complaint'], FULL),
      f('notes', 'textarea', ['Catatan', 'Notes'], FULL),
      f('coupon', 'text', ['Kupon', 'Coupon']),
      f('referral', 'text', ['Kode referral', 'Referral code']),
      f('meet_url', 'url', ['Link video', 'Video link'], { readonly: true }),
      f('source', 'text', ['Sumber', 'Source'], { readonly: true, default: 'admin' }),
      f('visit_id', 'ref', ['Kunjungan', 'Visit'], { ref: 'visits', readonly: true }),
      f('checkin_at', 'datetime', ['Check-in', 'Check-in'], { readonly: true }),
      f('reminded', 'bool', ['Pengingat terkirim', 'Reminder sent'], { readonly: true }),
    ],
  },
  visits: {
    store: 'd1', group: 'clinical', icon: 'clipboard', label: ['Kunjungan & Antrian', 'Visits & Queue'], labelField: 'visit_no', branch: 'branch_id', dateField: 'date',
    unique: ['visit_no'], indexes: ['branch_id,date', 'patient_id', 'doctor_id,date', 'status'],
    fields: [
      f('visit_no', 'text', ['No. kunjungan', 'Visit no.'], { readonly: true, auto: 'visit', ...L, ...S }),
      f('queue_no', 'text', ['No. antrian', 'Queue no.'], { readonly: true, ...L }),
      f('date', 'date', ['Tanggal', 'Date'], { ...L, readonly: true }),
      f('patient_id', 'ref', ['Pasien', 'Patient'], { ref: 'patients', ...R, ...L }),
      f('branch_id', 'ref', ['Cabang', 'Branch'], { ref: 'branches', ...R, filter: true }),
      f('poli_id', 'ref', ['Poli', 'Unit'], { ref: 'polis', ...R, ...L, filter: true }),
      f('doctor_id', 'ref', ['Dokter', 'Doctor'], { ref: 'doctors', ...L, filter: true }),
      f('queue_status', 'select', ['Status antrian', 'Queue status'], { options: OPTIONS.queueStatus, default: 'waiting', ...L }),
      f('status', 'select', ['Status kunjungan', 'Visit status'], { options: OPTIONS.visitStatus, default: 'registered', ...L, filter: true }),
      f('payer_type', 'select', ['Penjamin', 'Payer'], { options: OPTIONS.payer, default: 'umum' }),
      f('insurer_id', 'ref', ['Asuransi', 'Insurer'], { ref: 'insurers' }),
      f('complaint', 'textarea', ['Keluhan utama', 'Chief complaint'], FULL),
      f('appointment_id', 'ref', ['Booking', 'Booking'], { ref: 'appointments', readonly: true }),
      f('queue_seq', 'number', ['Urutan', 'Sequence'], { hidden: true }),
      f('called_at', 'datetime', ['Dipanggil', 'Called at'], { readonly: true }),
      f('finished_at', 'datetime', ['Selesai', 'Finished at'], { readonly: true }),
    ],
  },
  medical_records: {
    store: 'd1', group: 'clinical', icon: 'heart', label: ['Rekam Medis (ERM)', 'Medical Records (EMR)'], labelField: 'id', branch: 'branch_id', dateField: 'date',
    unique: ['visit_id'], indexes: ['patient_id,date', 'doctor_id,date', 'branch_id,date'],
    fields: [
      f('date', 'date', ['Tanggal', 'Date'], { ...L, readonly: true }),
      f('visit_id', 'ref', ['Kunjungan', 'Visit'], { ref: 'visits', ...R, ...L }),
      f('patient_id', 'ref', ['Pasien', 'Patient'], { ref: 'patients', ...R, ...L }),
      f('doctor_id', 'ref', ['Dokter', 'Doctor'], { ref: 'doctors', ...L, filter: true }),
      f('branch_id', 'ref', ['Cabang', 'Branch'], { ref: 'branches' }),
      f('vitals', 'json', ['Tanda vital', 'Vital signs'], { hidden: true }),
      f('anamnesis', 'textarea', ['Anamnesis', 'History taking'], FULL),
      f('subjective', 'textarea', ['S — Subjektif', 'S — Subjective'], FULL),
      f('physical_exam', 'textarea', ['Pemeriksaan fisik', 'Physical examination'], FULL),
      f('objective', 'textarea', ['O — Objektif', 'O — Objective'], FULL),
      f('assessment', 'textarea', ['A — Asesmen', 'A — Assessment'], FULL),
      f('plan', 'textarea', ['P — Rencana', 'P — Plan'], FULL),
      f('diagnoses', 'items', ['Diagnosis (ICD-10)', 'Diagnoses (ICD-10)'], { ...FULL, columns: [f('code', 'text', ['Kode', 'Code']), f('name', 'text', ['Diagnosis', 'Diagnosis']), f('primary', 'bool', ['Utama', 'Primary'])] }),
      f('procedures', 'items', ['Tindakan', 'Procedures'], { ...FULL, columns: [f('procedure_id', 'ref', ['Tindakan', 'Procedure'], { ref: 'procedures' }), f('name', 'text', ['Nama', 'Name']), f('qty', 'number', ['Qty', 'Qty']), f('price', 'money', ['Tarif', 'Fee']), f('by', 'text', ['Oleh', 'By'])] }),
      f('therapy', 'textarea', ['Terapi', 'Therapy'], FULL),
      f('notes', 'textarea', ['Catatan dokter', 'Doctor notes'], FULL),
      f('attachments', 'json', ['Lampiran', 'Attachments'], { hidden: true }),
      f('status', 'select', ['Status', 'Status'], { options: [['draft', 'Draf', 'Draft'], ['final', 'Final', 'Final']], default: 'draft', ...L }),
      f('signed_at', 'datetime', ['Ditandatangani', 'Signed at'], { readonly: true }),
    ],
  },
  prescriptions: {
    store: 'd1', group: 'pharmacy', icon: 'pill', label: ['Resep', 'Prescriptions'], labelField: 'rx_no', branch: 'branch_id', dateField: 'date',
    unique: ['rx_no'], indexes: ['branch_id,status', 'patient_id', 'visit_id', 'date'],
    fields: [
      f('rx_no', 'text', ['No. resep', 'Rx no.'], { readonly: true, auto: 'rx', ...L, ...S }),
      f('date', 'date', ['Tanggal', 'Date'], { ...L, readonly: true }),
      f('patient_id', 'ref', ['Pasien', 'Patient'], { ref: 'patients', ...R, ...L }),
      f('visit_id', 'ref', ['Kunjungan', 'Visit'], { ref: 'visits' }),
      f('doctor_id', 'ref', ['Dokter', 'Doctor'], { ref: 'doctors', ...L }),
      f('branch_id', 'ref', ['Cabang', 'Branch'], { ref: 'branches', ...R, filter: true }),
      f('items', 'items', ['Obat', 'Medicines'], { ...FULL, columns: [f('medicine_id', 'ref', ['Obat', 'Medicine'], { ref: 'medicines' }), f('name', 'text', ['Nama', 'Name']), f('qty', 'number', ['Qty', 'Qty']), f('unit', 'text', ['Satuan', 'Unit']), f('dose', 'text', ['Aturan pakai', 'Dosage']), f('price', 'money', ['Harga', 'Price'])] }),
      f('status', 'select', ['Status', 'Status'], { options: OPTIONS.rxStatus, default: 'new', ...L, filter: true }),
      f('notes', 'textarea', ['Catatan', 'Notes'], FULL),
      f('dispensed_by', 'text', ['Diserahkan oleh', 'Dispensed by'], { readonly: true }),
      f('dispensed_at', 'datetime', ['Waktu diserahkan', 'Dispensed at'], { readonly: true }),
    ],
  },
  lab_orders: {
    store: 'd1', group: 'clinical', icon: 'flask', label: ['Laboratorium', 'Laboratory'], labelField: 'lab_no', branch: 'branch_id', dateField: 'date',
    unique: ['lab_no'], indexes: ['branch_id,status', 'patient_id', 'visit_id', 'date'],
    fields: [
      f('lab_no', 'text', ['No. lab', 'Lab no.'], { readonly: true, auto: 'lab', ...L, ...S }),
      f('date', 'date', ['Tanggal', 'Date'], { ...L, readonly: true }),
      f('patient_id', 'ref', ['Pasien', 'Patient'], { ref: 'patients', ...R, ...L }),
      f('visit_id', 'ref', ['Kunjungan', 'Visit'], { ref: 'visits' }),
      f('doctor_id', 'ref', ['Dokter pengirim', 'Ordering doctor'], { ref: 'doctors', ...L }),
      f('branch_id', 'ref', ['Cabang', 'Branch'], { ref: 'branches', ...R, filter: true }),
      f('tests', 'items', ['Pemeriksaan & hasil', 'Tests & results'], { ...FULL, columns: [f('test_id', 'ref', ['Pemeriksaan', 'Test'], { ref: 'lab_tests' }), f('name', 'text', ['Nama', 'Name']), f('result', 'text', ['Hasil', 'Result']), f('unit', 'text', ['Satuan', 'Unit']), f('ref', 'text', ['Rujukan', 'Reference']), f('flag', 'select', ['Flag', 'Flag'], { options: OPTIONS.labFlag }), f('price', 'money', ['Tarif', 'Fee'])] }),
      f('status', 'select', ['Status', 'Status'], { options: OPTIONS.labStatus, default: 'requested', ...L, filter: true }),
      f('notes', 'textarea', ['Catatan klinis', 'Clinical notes'], FULL),
      f('validated_by', 'text', ['Divalidasi oleh', 'Validated by'], { readonly: true }),
      f('result_at', 'datetime', ['Waktu hasil', 'Result time'], { readonly: true }),
    ],
  },
  invoices: {
    store: 'd1', group: 'finance', icon: 'receipt', label: ['Invoice / Billing', 'Invoices / Billing'], labelField: 'invoice_no', branch: 'branch_id', dateField: 'date',
    unique: ['invoice_no'], indexes: ['branch_id,date', 'patient_id', 'visit_id', 'status,date'],
    fields: [
      f('invoice_no', 'text', ['No. invoice', 'Invoice no.'], { readonly: true, auto: 'invoice', ...L, ...S }),
      f('date', 'date', ['Tanggal', 'Date'], { ...L }),
      f('patient_id', 'ref', ['Pasien', 'Patient'], { ref: 'patients', ...L }),
      f('customer_name', 'text', ['Nama pelanggan (non pasien)', 'Customer name'], S),
      f('visit_id', 'ref', ['Kunjungan', 'Visit'], { ref: 'visits' }),
      f('branch_id', 'ref', ['Cabang', 'Branch'], { ref: 'branches', ...R, filter: true }),
      f('type', 'select', ['Jenis', 'Type'], { options: OPTIONS.invType, default: 'visit', filter: true }),
      f('items', 'items', ['Rincian', 'Line items'], { ...FULL, columns: [f('kind', 'select', ['Jenis', 'Kind'], { options: OPTIONS.itemKind }), f('name', 'text', ['Deskripsi', 'Description']), f('qty', 'number', ['Qty', 'Qty']), f('price', 'money', ['Harga', 'Price']), f('discount', 'money', ['Diskon', 'Discount'])] }),
      f('subtotal', 'money', ['Subtotal', 'Subtotal'], { readonly: true }),
      f('discount', 'money', ['Diskon tambahan', 'Extra discount'], { default: 0 }),
      f('tax', 'money', ['Pajak', 'Tax'], { readonly: true }),
      f('total', 'money', ['Total', 'Total'], { readonly: true, ...L }),
      f('paid', 'money', ['Terbayar', 'Paid'], { readonly: true, ...L }),
      f('status', 'select', ['Status', 'Status'], { options: OPTIONS.invStatus, default: 'unpaid', ...L, filter: true }),
      f('payer_type', 'select', ['Penjamin', 'Payer'], { options: OPTIONS.payer, default: 'umum' }),
      f('insurer_id', 'ref', ['Asuransi', 'Insurer'], { ref: 'insurers' }),
      f('coupon', 'text', ['Kupon', 'Coupon']),
      f('notes', 'textarea', ['Catatan', 'Notes'], FULL),
      f('pdf_key', 'hidden', ['', ''], { hidden: true }),
    ],
  },
  payments: {
    store: 'd1', group: 'finance', icon: 'wallet', label: ['Pembayaran', 'Payments'], labelField: 'payment_no', branch: 'branch_id', dateField: 'date',
    unique: ['payment_no'], indexes: ['invoice_id', 'branch_id,date', 'status', 'gateway_ref'],
    fields: [
      f('payment_no', 'text', ['No. pembayaran', 'Payment no.'], { readonly: true, auto: 'payment', ...L, ...S }),
      f('date', 'date', ['Tanggal', 'Date'], L),
      f('invoice_id', 'ref', ['Invoice', 'Invoice'], { ref: 'invoices', ...R, ...L }),
      f('patient_id', 'ref', ['Pasien', 'Patient'], { ref: 'patients' }),
      f('branch_id', 'ref', ['Cabang', 'Branch'], { ref: 'branches', filter: true }),
      f('method', 'select', ['Metode', 'Method'], { options: OPTIONS.payMethod, ...R, ...L, filter: true }),
      f('amount', 'money', ['Jumlah', 'Amount'], { ...R, ...L }),
      f('status', 'select', ['Status', 'Status'], { options: OPTIONS.payStatus, default: 'confirmed', ...L, filter: true }),
      f('reference', 'text', ['Referensi', 'Reference'], S),
      f('proof', 'file', ['Bukti bayar', 'Payment proof'], { private: true }),
      f('gateway_ref', 'text', ['Ref. gateway', 'Gateway ref.'], { readonly: true }),
      f('confirmed_by', 'text', ['Dikonfirmasi oleh', 'Confirmed by'], { readonly: true }),
      f('notes', 'textarea', ['Catatan', 'Notes'], FULL),
    ],
  },
  refunds: {
    store: 'd1', group: 'finance', icon: 'rotate', label: ['Refund', 'Refunds'], labelField: 'refund_no', branch: 'branch_id', dateField: 'date',
    unique: ['refund_no'], indexes: ['invoice_id', 'payment_id'],
    fields: [
      f('refund_no', 'text', ['No. refund', 'Refund no.'], { readonly: true, auto: 'refund', ...L }),
      f('date', 'date', ['Tanggal', 'Date'], L),
      f('payment_id', 'ref', ['Pembayaran', 'Payment'], { ref: 'payments', ...R, ...L }),
      f('invoice_id', 'ref', ['Invoice', 'Invoice'], { ref: 'invoices', ...L }),
      f('branch_id', 'ref', ['Cabang', 'Branch'], { ref: 'branches' }),
      f('amount', 'money', ['Jumlah', 'Amount'], { ...R, ...L }),
      f('reason', 'textarea', ['Alasan', 'Reason'], { ...R, ...FULL }),
      f('status', 'select', ['Status', 'Status'], { options: [['requested', 'Diajukan', 'Requested'], ['processed', 'Diproses', 'Processed'], ['rejected', 'Ditolak', 'Rejected']], default: 'processed', ...L }),
      f('processed_by', 'text', ['Diproses oleh', 'Processed by'], { readonly: true }),
    ],
  },
  claims: {
    store: 'd1', group: 'finance', icon: 'shield', label: ['Klaim BPJS / Asuransi', 'Insurance Claims'], labelField: 'claim_no', branch: 'branch_id', dateField: 'date',
    unique: ['claim_no'], indexes: ['insurer_id,status', 'invoice_id'],
    fields: [
      f('claim_no', 'text', ['No. klaim', 'Claim no.'], { readonly: true, auto: 'claim', ...L, ...S }),
      f('date', 'date', ['Tanggal', 'Date'], L),
      f('invoice_id', 'ref', ['Invoice', 'Invoice'], { ref: 'invoices', ...L }),
      f('patient_id', 'ref', ['Pasien', 'Patient'], { ref: 'patients', ...L }),
      f('insurer_id', 'ref', ['Penjamin', 'Payer'], { ref: 'insurers', ...R, ...L, filter: true }),
      f('branch_id', 'ref', ['Cabang', 'Branch'], { ref: 'branches' }),
      f('member_no', 'text', ['No. peserta', 'Member no.']),
      f('sep_no', 'text', ['No. SEP / GL', 'SEP / GL no.'], S),
      f('amount', 'money', ['Nilai klaim', 'Claim amount'], { ...R, ...L }),
      f('approved_amount', 'money', ['Nilai disetujui', 'Approved amount'], L),
      f('status', 'select', ['Status', 'Status'], { options: OPTIONS.claimStatus, default: 'draft', ...L, filter: true }),
      f('submitted_at', 'date', ['Tanggal diajukan', 'Submitted on']),
      f('notes', 'textarea', ['Catatan', 'Notes'], FULL),
    ],
  },
  medicines: {
    store: 'd1', group: 'pharmacy', icon: 'pill', label: ['Master Obat', 'Medicines'], labelField: 'name', labelExtra: 'strength',
    unique: ['code'], indexes: ['name', 'category'],
    fields: [
      f('code', 'text', ['Kode obat', 'Code'], { ...L, ...S }),
      f('name', 'text', ['Nama obat', 'Name'], { ...R, ...L, ...S }),
      f('generic_name', 'text', ['Nama generik', 'Generic name'], S),
      f('category', 'ref', ['Kategori', 'Category'], { ref: 'medicine_categories', ...L, filter: true }),
      f('form', 'text', ['Sediaan', 'Dosage form'], { help: 'Tablet, kapsul, sirup, salep, injeksi…' }),
      f('strength', 'text', ['Kekuatan', 'Strength'], L),
      f('unit', 'ref', ['Satuan', 'Unit'], { ref: 'units', ...L }),
      f('manufacturer', 'text', ['Pabrikan', 'Manufacturer']),
      f('price_buy', 'money', ['Harga beli', 'Purchase price']),
      f('price_sell', 'money', ['Harga jual', 'Selling price'], { ...R, ...L }),
      f('min_stock', 'number', ['Stok minimum', 'Minimum stock'], { default: 10 }),
      f('requires_rx', 'bool', ['Wajib resep', 'Prescription only']),
      f('kfa_code', 'text', ['Kode KFA (SATU SEHAT)', 'KFA code']),
      f('is_active', 'bool', ['Aktif', 'Active'], { ...L, default: true }),
    ],
  },
  stock_batches: {
    store: 'd1', group: 'pharmacy', icon: 'layers', label: ['Stok per Batch', 'Stock Batches'], labelField: 'batch_no', branch: 'branch_id', noCreate: true,
    indexes: ['medicine_id,branch_id,expired_at', 'branch_id,expired_at'],
    fields: [
      f('medicine_id', 'ref', ['Obat', 'Medicine'], { ref: 'medicines', ...R, ...L }),
      f('branch_id', 'ref', ['Cabang', 'Branch'], { ref: 'branches', ...R, ...L, filter: true }),
      f('batch_no', 'text', ['No. batch', 'Batch no.'], { ...L, ...S }),
      f('expired_at', 'date', ['Kedaluwarsa', 'Expiry'], L),
      f('qty', 'number', ['Qty', 'Qty'], { ...L, readonly: true, check: 'qty >= 0', default: 0 }),
      f('cost', 'money', ['HPP', 'Unit cost'], L),
      f('supplier_id', 'ref', ['Supplier', 'Supplier'], { ref: 'suppliers' }),
    ],
  },
  stock_moves: {
    store: 'd1', group: 'pharmacy', icon: 'repeat', label: ['Mutasi Stok', 'Stock Movements'], labelField: 'id', branch: 'branch_id', dateField: 'date', readonly: true,
    indexes: ['medicine_id,created_at', 'branch_id,date', 'type,date'],
    fields: [
      f('date', 'date', ['Tanggal', 'Date'], L),
      f('medicine_id', 'ref', ['Obat', 'Medicine'], { ref: 'medicines', ...L }),
      f('branch_id', 'ref', ['Cabang', 'Branch'], { ref: 'branches', ...L, filter: true }),
      f('batch_id', 'ref', ['Batch', 'Batch'], { ref: 'stock_batches' }),
      f('type', 'select', ['Jenis', 'Type'], { options: OPTIONS.moveType, ...L, filter: true }),
      f('qty', 'number', ['Qty', 'Qty'], L),
      f('balance', 'number', ['Saldo batch', 'Batch balance'], L),
      f('ref', 'text', ['Referensi', 'Reference'], { ...L, ...S }),
      f('note', 'text', ['Catatan', 'Note']),
      f('user_name', 'text', ['Petugas', 'User'], L),
    ],
  },
  suppliers: {
    store: 'd1', group: 'pharmacy', icon: 'truck', label: ['Supplier', 'Suppliers'], labelField: 'name',
    fields: [
      f('name', 'text', ['Nama supplier', 'Supplier'], { ...R, ...L, ...S }),
      f('contact', 'text', ['Kontak', 'Contact person'], L),
      f('phone', 'phone', ['Telepon', 'Phone'], L),
      f('email', 'email', ['Email', 'Email']),
      f('address', 'textarea', ['Alamat', 'Address'], FULL),
      f('npwp', 'text', ['NPWP', 'Tax ID']),
      f('terms', 'text', ['Termin pembayaran', 'Payment terms']),
      f('active', 'bool', ['Aktif', 'Active'], { ...L, default: true }),
    ],
  },
  purchase_orders: {
    store: 'd1', group: 'pharmacy', icon: 'cart', label: ['Purchase Order', 'Purchase Orders'], labelField: 'po_no', branch: 'branch_id', dateField: 'date',
    unique: ['po_no'], indexes: ['branch_id,date', 'supplier_id', 'status'],
    fields: [
      f('po_no', 'text', ['No. PO', 'PO no.'], { readonly: true, auto: 'po', ...L, ...S }),
      f('date', 'date', ['Tanggal', 'Date'], { ...L, ...R }),
      f('supplier_id', 'ref', ['Supplier', 'Supplier'], { ref: 'suppliers', ...R, ...L }),
      f('branch_id', 'ref', ['Cabang', 'Branch'], { ref: 'branches', ...R, ...L, filter: true }),
      f('items', 'items', ['Item', 'Items'], { ...FULL, columns: [f('medicine_id', 'ref', ['Obat', 'Medicine'], { ref: 'medicines' }), f('qty', 'number', ['Qty', 'Qty']), f('cost', 'money', ['Harga', 'Cost']), f('batch_no', 'text', ['Batch', 'Batch']), f('expired_at', 'date', ['Exp.', 'Exp.'])] }),
      f('total', 'money', ['Total', 'Total'], { readonly: true, ...L }),
      f('status', 'select', ['Status', 'Status'], { options: OPTIONS.poStatus, default: 'draft', ...L, filter: true }),
      f('received_at', 'datetime', ['Diterima', 'Received at'], { readonly: true }),
      f('notes', 'textarea', ['Catatan', 'Notes'], FULL),
    ],
  },
  coupons: {
    store: 'd1', group: 'crm', icon: 'ticket', label: ['Kupon', 'Coupons'], labelField: 'code', unique: ['code'],
    fields: [
      f('code', 'text', ['Kode kupon', 'Code'], { ...R, ...L, ...S }),
      f('description', 'text', ['Deskripsi', 'Description'], L),
      f('type', 'select', ['Jenis', 'Type'], { options: OPTIONS.couponType, default: 'percent', ...L }),
      f('value', 'number', ['Nilai', 'Value'], { ...R, ...L }),
      f('min_amount', 'money', ['Minimal transaksi', 'Min. amount'], { default: 0 }),
      f('max_uses', 'number', ['Maks. pemakaian (0 = tak terbatas)', 'Max uses (0 = unlimited)'], { default: 0 }),
      f('used', 'number', ['Terpakai', 'Used'], { readonly: true, default: 0, ...L }),
      f('start_date', 'date', ['Mulai', 'Start']),
      f('end_date', 'date', ['Berakhir', 'End'], L),
      f('active', 'bool', ['Aktif', 'Active'], { ...L, default: true }),
    ],
  },
  corporates: {
    store: 'd1', group: 'crm', icon: 'briefcase', label: ['Pasien Korporat', 'Corporate Clients'], labelField: 'name',
    fields: [
      f('name', 'text', ['Nama perusahaan', 'Company'], { ...R, ...L, ...S }),
      f('contact', 'text', ['PIC', 'Contact person'], L),
      f('phone', 'phone', ['Telepon', 'Phone'], L),
      f('email', 'email', ['Email', 'Email']),
      f('address', 'textarea', ['Alamat', 'Address'], FULL),
      f('discount_pct', 'number', ['Diskon (%)', 'Discount (%)'], { default: 0, ...L }),
      f('contract_until', 'date', ['Kontrak hingga', 'Contract until'], L),
      f('notes', 'textarea', ['Catatan', 'Notes'], FULL),
      f('active', 'bool', ['Aktif', 'Active'], { ...L, default: true }),
    ],
  },
  leads: {
    store: 'd1', group: 'crm', icon: 'inbox', label: ['Lead & Pesan Masuk', 'Leads & Inbox'], labelField: 'name', dateField: 'date', indexes: ['status,date'],
    fields: [
      f('date', 'date', ['Tanggal', 'Date'], L),
      f('name', 'text', ['Nama', 'Name'], { ...R, ...L, ...S }),
      f('phone', 'phone', ['No. HP', 'Phone'], { ...L, ...S }),
      f('email', 'email', ['Email', 'Email'], S),
      f('source', 'text', ['Sumber', 'Source'], { ...L, filter: true }),
      f('interest', 'text', ['Minat', 'Interest'], L),
      f('message', 'textarea', ['Pesan', 'Message'], FULL),
      f('status', 'select', ['Status', 'Status'], { options: OPTIONS.leadStatus, default: 'new', ...L, filter: true }),
      f('notes', 'textarea', ['Catatan tindak lanjut', 'Follow-up notes'], FULL),
    ],
  },
  newsletter: {
    store: 'd1', group: 'crm', icon: 'mail', label: ['Newsletter', 'Newsletter'], labelField: 'email', unique: ['email'],
    fields: [
      f('email', 'email', ['Email', 'Email'], { ...R, ...L, ...S }),
      f('name', 'text', ['Nama', 'Name'], L),
      f('status', 'select', ['Status', 'Status'], { options: [['subscribed', 'Berlangganan', 'Subscribed'], ['unsubscribed', 'Berhenti', 'Unsubscribed']], default: 'subscribed', ...L }),
    ],
  },
  documents: {
    store: 'd1', group: 'clinical', icon: 'paperclip', label: ['Dokumen Medis', 'Medical Documents'], labelField: 'title', indexes: ['patient_id', 'visit_id'],
    fields: [
      f('title', 'text', ['Judul dokumen', 'Title'], { ...R, ...L, ...S }),
      f('patient_id', 'ref', ['Pasien', 'Patient'], { ref: 'patients', ...R, ...L }),
      f('visit_id', 'ref', ['Kunjungan', 'Visit'], { ref: 'visits' }),
      f('category', 'select', ['Kategori', 'Category'], { options: OPTIONS.docCategory, ...L, filter: true }),
      f('file', 'file', ['File', 'File'], { ...R, private: true }),
      f('shared_with_patient', 'bool', ['Tampilkan di portal pasien', 'Show in patient portal'], { default: true, ...L }),
      f('notes', 'textarea', ['Catatan', 'Notes'], FULL),
      f('uploaded_by', 'text', ['Diunggah oleh', 'Uploaded by'], { readonly: true, ...L }),
    ],
  },
  loyalty_ledger: {
    store: 'd1', group: 'crm', icon: 'award', label: ['Riwayat Poin', 'Points Ledger'], labelField: 'id', indexes: ['patient_id'],
    fields: [
      f('patient_id', 'ref', ['Pasien', 'Patient'], { ref: 'patients', ...R, ...L }),
      f('points', 'number', ['Poin (+/-)', 'Points (+/-)'], { ...R, ...L }),
      f('reason', 'text', ['Keterangan', 'Reason'], { ...L, ...S }),
      f('ref', 'text', ['Referensi', 'Reference'], L),
    ],
  },
  notif_log: {
    store: 'd1', group: 'system', icon: 'bell', label: ['Log Notifikasi', 'Notification Log'], labelField: 'id', readonly: true, indexes: ['created_at'],
    fields: [
      f('channel', 'text', ['Kanal', 'Channel'], { ...L, filter: true }),
      f('recipient', 'text', ['Penerima', 'Recipient'], { ...L, ...S }),
      f('subject', 'text', ['Subjek', 'Subject'], L),
      f('body', 'textarea', ['Isi', 'Body'], FULL),
      f('status', 'text', ['Status', 'Status'], L),
      f('ref', 'text', ['Referensi', 'Reference'], L),
      f('link', 'url', ['Link WA manual', 'Manual WA link']),
    ],
  },
  satusehat_sync: {
    store: 'd1', group: 'system', icon: 'refresh', label: ['Sinkron SATU SEHAT', 'SATU SEHAT Sync'], labelField: 'id', readonly: true, indexes: ['status', 'resource,local_id'],
    fields: [
      f('resource', 'text', ['Resource FHIR', 'FHIR resource'], { ...L, filter: true }),
      f('local_id', 'text', ['ID lokal', 'Local ID'], L),
      f('fhir_id', 'text', ['ID FHIR', 'FHIR ID'], L),
      f('status', 'select', ['Status', 'Status'], { options: OPTIONS.syncStatus, ...L, filter: true }),
      f('attempts', 'number', ['Percobaan', 'Attempts'], L),
      f('error', 'textarea', ['Error', 'Error'], FULL),
    ],
  },
  audit_logs: {
    store: 'd1', group: 'system', icon: 'list', label: ['Audit Log', 'Audit Log'], labelField: 'id', readonly: true, dateField: 'date', indexes: ['date', 'entity,entity_id', 'user_id'],
    fields: [
      f('date', 'date', ['Tanggal', 'Date'], L),
      f('username', 'text', ['Pengguna', 'User'], { ...L, ...S }),
      f('role', 'text', ['Peran', 'Role'], L),
      f('action', 'text', ['Aksi', 'Action'], { ...L, filter: true }),
      f('entity', 'text', ['Entitas', 'Entity'], { ...L, filter: true }),
      f('entity_id', 'text', ['ID', 'ID'], L),
      f('ip', 'text', ['IP', 'IP'], L),
      f('detail', 'textarea', ['Detail', 'Detail'], FULL),
      f('user_id', 'number', ['User ID', 'User ID'], { hidden: true }),
    ],
  },
};

// Default D1 index hints for every D1 table are created by scripts/gen-schema.mjs
export function entity(name) {
  const e = ENTITIES[name];
  return e ? { name, ...e } : null;
}

// Special (non-entity) permission keys used by workflow screens
export const SPECIAL_PERMS = [
  ['dashboard:view', 'Lihat dashboard', 'View dashboard'],
  ['queue:call', 'Panggil antrian', 'Call queue'],
  ['clinic:register', 'Pendaftaran kunjungan', 'Register visits'],
  ['clinic:examine', 'Pemeriksaan dokter (SOAP)', 'Doctor examination'],
  ['clinic:triage', 'Triase & tanda vital', 'Triage & vitals'],
  ['pharmacy:dispense', 'Dispensing resep', 'Dispense prescriptions'],
  ['pharmacy:sale', 'Penjualan obat bebas', 'OTC sales'],
  ['pharmacy:stock', 'Kelola stok (masuk, opname, mutasi)', 'Manage stock'],
  ['lab:process', 'Proses & validasi lab', 'Process lab'],
  ['billing:cashier', 'Kasir (terima pembayaran)', 'Cashier'],
  ['billing:refund', 'Proses refund', 'Process refunds'],
  ['reports:view', 'Lihat laporan', 'View reports'],
  ['reports:export', 'Ekspor laporan', 'Export reports'],
  ['media:manage', 'Kelola media (R2)', 'Manage media'],
  ['settings:update', 'Ubah pengaturan', 'Update settings'],
  ['system:backup', 'Backup & restore', 'Backup & restore'],
  ['system:satusehat', 'Kelola SATU SEHAT', 'Manage SATU SEHAT'],
];
